<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CiudadesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('ciudades')->insert([
            ['id' => 1, 'ciudad' => 'Abriaquí', 'depto_id' => 5],
            ['id' => 2, 'ciudad' => 'Acacías', 'depto_id' => 50],
            ['id' => 3, 'ciudad' => 'Acandí', 'depto_id' => 27],
            ['id' => 4, 'ciudad' => 'Acevedo', 'depto_id' => 41],
            ['id' => 5, 'ciudad' => 'Achí', 'depto_id' => 13],
            ['id' => 6, 'ciudad' => 'Agrado', 'depto_id' => 41],
            ['id' => 7, 'ciudad' => 'Agua de Dios', 'depto_id' => 25],
            ['id' => 8, 'ciudad' => 'Aguachica', 'depto_id' => 20],
            ['id' => 9, 'ciudad' => 'Aguada', 'depto_id' => 68],
            ['id' => 10, 'ciudad' => 'Aguadas', 'depto_id' => 17],
            ['id' => 11, 'ciudad' => 'Aguazul', 'depto_id' => 85],
            ['id' => 12, 'ciudad' => 'Agustín Codazzi', 'depto_id' => 20],
            ['id' => 13, 'ciudad' => 'Aipe', 'depto_id' => 41],
            ['id' => 14, 'ciudad' => 'Albania', 'depto_id' => 18],
            ['id' => 15, 'ciudad' => 'Albania', 'depto_id' => 44],
            ['id' => 16, 'ciudad' => 'Albania', 'depto_id' => 68],
            ['id' => 17, 'ciudad' => 'Albán', 'depto_id' => 25],
            ['id' => 18, 'ciudad' => 'Albán (San José)', 'depto_id' => 52],
            ['id' => 19, 'ciudad' => 'Alcalá', 'depto_id' => 76],
            ['id' => 20, 'ciudad' => 'Alejandria', 'depto_id' => 5],
            ['id' => 21, 'ciudad' => 'Algarrobo', 'depto_id' => 47],
            ['id' => 22, 'ciudad' => 'Algeciras', 'depto_id' => 41],
            ['id' => 23, 'ciudad' => 'Almaguer', 'depto_id' => 19],
            ['id' => 24, 'ciudad' => 'Almeida', 'depto_id' => 15],
            ['id' => 25, 'ciudad' => 'Alpujarra', 'depto_id' => 73],
            ['id' => 26, 'ciudad' => 'Altamira', 'depto_id' => 41],
            ['id' => 27, 'ciudad' => 'Alto Baudó (Pie de Pato)', 'depto_id' => 27],
            ['id' => 28, 'ciudad' => 'Altos del Rosario', 'depto_id' => 13],
            ['id' => 29, 'ciudad' => 'Alvarado', 'depto_id' => 73],
            ['id' => 30, 'ciudad' => 'Amagá', 'depto_id' => 5],
            ['id' => 31, 'ciudad' => 'Amalfi', 'depto_id' => 5],
            ['id' => 32, 'ciudad' => 'Ambalema', 'depto_id' => 73],
            ['id' => 33, 'ciudad' => 'Anapoima', 'depto_id' => 25],
            ['id' => 34, 'ciudad' => 'Ancuya', 'depto_id' => 52],
            ['id' => 35, 'ciudad' => 'Andalucía', 'depto_id' => 76],
            ['id' => 36, 'ciudad' => 'Andes', 'depto_id' => 5],
            ['id' => 37, 'ciudad' => 'Angelópolis', 'depto_id' => 5],
            ['id' => 38, 'ciudad' => 'Angostura', 'depto_id' => 5],
            ['id' => 39, 'ciudad' => 'Anolaima', 'depto_id' => 25],
            ['id' => 40, 'ciudad' => 'Anorí', 'depto_id' => 5],
            ['id' => 41, 'ciudad' => 'Anserma', 'depto_id' => 17],
            ['id' => 42, 'ciudad' => 'Ansermanuevo', 'depto_id' => 76],
            ['id' => 43, 'ciudad' => 'Anzoátegui', 'depto_id' => 73],
            ['id' => 44, 'ciudad' => 'Anzá', 'depto_id' => 5],
            ['id' => 45, 'ciudad' => 'Apartadó', 'depto_id' => 5],
            ['id' => 46, 'ciudad' => 'Apulo', 'depto_id' => 25],
            ['id' => 47, 'ciudad' => 'Apía', 'depto_id' => 66],
            ['id' => 48, 'ciudad' => 'Aquitania', 'depto_id' => 15],
            ['id' => 49, 'ciudad' => 'Aracataca', 'depto_id' => 47],
            ['id' => 50, 'ciudad' => 'Aranzazu', 'depto_id' => 17],
            ['id' => 51, 'ciudad' => 'Aratoca', 'depto_id' => 68],
            ['id' => 52, 'ciudad' => 'Arauca', 'depto_id' => 81],
            ['id' => 53, 'ciudad' => 'Arauquita', 'depto_id' => 81],
            ['id' => 54, 'ciudad' => 'Arbeláez', 'depto_id' => 25],
            ['id' => 55, 'ciudad' => 'Arboleda (Berruecos)', 'depto_id' => 52],
            ['id' => 56, 'ciudad' => 'Arboledas', 'depto_id' => 54],
            ['id' => 57, 'ciudad' => 'Arboletes', 'depto_id' => 5],
            ['id' => 58, 'ciudad' => 'Arcabuco', 'depto_id' => 15],
            ['id' => 59, 'ciudad' => 'Arenal', 'depto_id' => 13],
            ['id' => 60, 'ciudad' => 'Argelia', 'depto_id' => 5],
            ['id' => 61, 'ciudad' => 'Argelia', 'depto_id' => 19],
            ['id' => 62, 'ciudad' => 'Argelia', 'depto_id' => 76],
            ['id' => 63, 'ciudad' => 'Ariguaní (El Difícil)', 'depto_id' => 47],
            ['id' => 64, 'ciudad' => 'Arjona', 'depto_id' => 13],
            ['id' => 65, 'ciudad' => 'Armenia', 'depto_id' => 5],
            ['id' => 66, 'ciudad' => 'Armenia', 'depto_id' => 63],
            ['id' => 67, 'ciudad' => 'Armero (Guayabal)', 'depto_id' => 73],
            ['id' => 68, 'ciudad' => 'Arroyohondo', 'depto_id' => 13],
            ['id' => 69, 'ciudad' => 'Astrea', 'depto_id' => 20],
            ['id' => 70, 'ciudad' => 'Ataco', 'depto_id' => 73],
            ['id' => 71, 'ciudad' => 'Atrato (Yuto)', 'depto_id' => 27],
            ['id' => 72, 'ciudad' => 'Ayapel', 'depto_id' => 23],
            ['id' => 73, 'ciudad' => 'Bagadó', 'depto_id' => 27],
            ['id' => 74, 'ciudad' => 'Bahía Solano (Mútis)', 'depto_id' => 27],
            ['id' => 75, 'ciudad' => 'Bajo Baudó (Pizarro)', 'depto_id' => 27],
            ['id' => 76, 'ciudad' => 'Balboa', 'depto_id' => 19],
            ['id' => 77, 'ciudad' => 'Balboa', 'depto_id' => 66],
            ['id' => 78, 'ciudad' => 'Baranoa', 'depto_id' => 8],
            ['id' => 79, 'ciudad' => 'Baraya', 'depto_id' => 41],
            ['id' => 80, 'ciudad' => 'Barbacoas', 'depto_id' => 52],
            ['id' => 81, 'ciudad' => 'Barbosa', 'depto_id' => 5],
            ['id' => 82, 'ciudad' => 'Barbosa', 'depto_id' => 68],
            ['id' => 83, 'ciudad' => 'Barichara', 'depto_id' => 68],
            ['id' => 84, 'ciudad' => 'Barranca de Upía', 'depto_id' => 50],
            ['id' => 85, 'ciudad' => 'Barrancabermeja', 'depto_id' => 68],
            ['id' => 86, 'ciudad' => 'Barrancas', 'depto_id' => 44],
            ['id' => 87, 'ciudad' => 'Barranco de Loba', 'depto_id' => 13],
            ['id' => 88, 'ciudad' => 'Barranquilla', 'depto_id' => 8],
            ['id' => 89, 'ciudad' => 'Becerríl', 'depto_id' => 20],
            ['id' => 90, 'ciudad' => 'Belalcázar', 'depto_id' => 17],
            ['id' => 91, 'ciudad' => 'Bello', 'depto_id' => 5],
            ['id' => 92, 'ciudad' => 'Belmira', 'depto_id' => 5],
            ['id' => 93, 'ciudad' => 'Beltrán', 'depto_id' => 25],
            ['id' => 94, 'ciudad' => 'Belén', 'depto_id' => 15],
            ['id' => 95, 'ciudad' => 'Belén', 'depto_id' => 52],
            ['id' => 96, 'ciudad' => 'Belén de Bajirá', 'depto_id' => 27],
            ['id' => 97, 'ciudad' => 'Belén de Umbría', 'depto_id' => 66],
            ['id' => 98, 'ciudad' => 'Belén de los Andaquíes', 'depto_id' => 18],
            ['id' => 99, 'ciudad' => 'Berbeo', 'depto_id' => 15],
            ['id' => 100, 'ciudad' => 'Betania', 'depto_id' => 5],
            ['id' => 101, 'ciudad' => 'Beteitiva', 'depto_id' => 15],
            ['id' => 102, 'ciudad' => 'Betulia', 'depto_id' => 5],
            ['id' => 103, 'ciudad' => 'Betulia', 'depto_id' => 68],
            ['id' => 104, 'ciudad' => 'Bituima', 'depto_id' => 25],
            ['id' => 105, 'ciudad' => 'Boavita', 'depto_id' => 15],
            ['id' => 106, 'ciudad' => 'Bochalema', 'depto_id' => 54],
            ['id' => 107, 'ciudad' => 'Bogotá D.C.', 'depto_id' => 11],
            ['id' => 108, 'ciudad' => 'Bojacá', 'depto_id' => 25],
            ['id' => 109, 'ciudad' => 'Bojayá (Bellavista)', 'depto_id' => 27],
            ['id' => 110, 'ciudad' => 'Bolívar', 'depto_id' => 5],
            ['id' => 111, 'ciudad' => 'Bolívar', 'depto_id' => 19],
            ['id' => 112, 'ciudad' => 'Bolívar', 'depto_id' => 68],
            ['id' => 113, 'ciudad' => 'Bolívar', 'depto_id' => 76],
            ['id' => 114, 'ciudad' => 'Bosconia', 'depto_id' => 20],
            ['id' => 115, 'ciudad' => 'Boyacá', 'depto_id' => 15],
            ['id' => 116, 'ciudad' => 'Briceño', 'depto_id' => 5],
            ['id' => 117, 'ciudad' => 'Briceño', 'depto_id' => 15],
            ['id' => 118, 'ciudad' => 'Bucaramanga', 'depto_id' => 68],
            ['id' => 119, 'ciudad' => 'Bucarasica', 'depto_id' => 54],
            ['id' => 120, 'ciudad' => 'Buenaventura', 'depto_id' => 76],
            ['id' => 121, 'ciudad' => 'Buenavista', 'depto_id' => 15],
            ['id' => 122, 'ciudad' => 'Buenavista', 'depto_id' => 23],
            ['id' => 123, 'ciudad' => 'Buenavista', 'depto_id' => 63],
            ['id' => 124, 'ciudad' => 'Buenavista', 'depto_id' => 70],
            ['id' => 125, 'ciudad' => 'Buenos Aires', 'depto_id' => 19],
            ['id' => 126, 'ciudad' => 'Buesaco', 'depto_id' => 52],
            ['id' => 127, 'ciudad' => 'Buga', 'depto_id' => 76],
            ['id' => 128, 'ciudad' => 'Bugalagrande', 'depto_id' => 76],
            ['id' => 129, 'ciudad' => 'Burítica', 'depto_id' => 5],
            ['id' => 130, 'ciudad' => 'Busbanza', 'depto_id' => 15],
            ['id' => 131, 'ciudad' => 'Cabrera', 'depto_id' => 25],
            ['id' => 132, 'ciudad' => 'Cabrera', 'depto_id' => 68],
            ['id' => 133, 'ciudad' => 'Cabuyaro', 'depto_id' => 50],
            ['id' => 134, 'ciudad' => 'Cachipay', 'depto_id' => 25],
            ['id' => 135, 'ciudad' => 'Caicedo', 'depto_id' => 5],
            ['id' => 136, 'ciudad' => 'Caicedonia', 'depto_id' => 76],
            ['id' => 137, 'ciudad' => 'Caimito', 'depto_id' => 70],
            ['id' => 138, 'ciudad' => 'Cajamarca', 'depto_id' => 73],
            ['id' => 139, 'ciudad' => 'Cajibío', 'depto_id' => 19],
            ['id' => 140, 'ciudad' => 'Cajicá', 'depto_id' => 25],
            ['id' => 141, 'ciudad' => 'Calamar', 'depto_id' => 13],
            ['id' => 142, 'ciudad' => 'Calamar', 'depto_id' => 95],
            ['id' => 143, 'ciudad' => 'Calarcá', 'depto_id' => 63],
            ['id' => 144, 'ciudad' => 'Caldas', 'depto_id' => 5],
            ['id' => 145, 'ciudad' => 'Caldas', 'depto_id' => 15],
            ['id' => 146, 'ciudad' => 'Caldono', 'depto_id' => 19],
            ['id' => 147, 'ciudad' => 'California', 'depto_id' => 68],
            ['id' => 148, 'ciudad' => 'Calima (Darién)', 'depto_id' => 76],
            ['id' => 149, 'ciudad' => 'Caloto', 'depto_id' => 19],
            ['id' => 150, 'ciudad' => 'Calí', 'depto_id' => 76],
            ['id' => 151, 'ciudad' => 'Campamento', 'depto_id' => 5],
            ['id' => 152, 'ciudad' => 'Campo de la Cruz', 'depto_id' => 8],
            ['id' => 153, 'ciudad' => 'Campoalegre', 'depto_id' => 41],
            ['id' => 154, 'ciudad' => 'Campohermoso', 'depto_id' => 15],
            ['id' => 155, 'ciudad' => 'Canalete', 'depto_id' => 23],
            ['id' => 156, 'ciudad' => 'Candelaria', 'depto_id' => 8],
            ['id' => 157, 'ciudad' => 'Candelaria', 'depto_id' => 76],
            ['id' => 158, 'ciudad' => 'Cantagallo', 'depto_id' => 13],
            ['id' => 159, 'ciudad' => 'Cantón de San Pablo', 'depto_id' => 27],
            ['id' => 160, 'ciudad' => 'Caparrapí', 'depto_id' => 25],
            ['id' => 161, 'ciudad' => 'Capitanejo', 'depto_id' => 68],
            ['id' => 162, 'ciudad' => 'Caracolí', 'depto_id' => 5],
            ['id' => 163, 'ciudad' => 'Caramanta', 'depto_id' => 5],
            ['id' => 164, 'ciudad' => 'Carcasí', 'depto_id' => 68],
            ['id' => 165, 'ciudad' => 'Carepa', 'depto_id' => 5],
            ['id' => 166, 'ciudad' => 'Carmen de Apicalá', 'depto_id' => 73],
            ['id' => 167, 'ciudad' => 'Carmen de Carupa', 'depto_id' => 25],
            ['id' => 168, 'ciudad' => 'Carmen de Viboral', 'depto_id' => 5],
            ['id' => 169, 'ciudad' => 'Carmen del Darién (CURBARADÓ)', 'depto_id' => 27],
            ['id' => 170, 'ciudad' => 'Carolina', 'depto_id' => 5],
            ['id' => 171, 'ciudad' => 'Cartagena', 'depto_id' => 13],
            ['id' => 172, 'ciudad' => 'Cartagena del Chairá', 'depto_id' => 18],
            ['id' => 173, 'ciudad' => 'Cartago', 'depto_id' => 76],
            ['id' => 174, 'ciudad' => 'Carurú', 'depto_id' => 97],
            ['id' => 175, 'ciudad' => 'Casabianca', 'depto_id' => 73],
            ['id' => 176, 'ciudad' => 'Castilla la Nueva', 'depto_id' => 50],
            ['id' => 177, 'ciudad' => 'Caucasia', 'depto_id' => 5],
            ['id' => 178, 'ciudad' => 'Cañasgordas', 'depto_id' => 5],
            ['id' => 179, 'ciudad' => 'Cepita', 'depto_id' => 68],
            ['id' => 180, 'ciudad' => 'Cereté', 'depto_id' => 23],
            ['id' => 181, 'ciudad' => 'Cerinza', 'depto_id' => 15],
            ['id' => 182, 'ciudad' => 'Cerrito', 'depto_id' => 68],
            ['id' => 183, 'ciudad' => 'Cerro San Antonio', 'depto_id' => 47],
            ['id' => 184, 'ciudad' => 'Chachaguí', 'depto_id' => 52],
            ['id' => 185, 'ciudad' => 'Chaguaní', 'depto_id' => 25],
            ['id' => 186, 'ciudad' => 'Chalán', 'depto_id' => 70],
            ['id' => 187, 'ciudad' => 'Chaparral', 'depto_id' => 73],
            ['id' => 188, 'ciudad' => 'Charalá', 'depto_id' => 68],
            ['id' => 189, 'ciudad' => 'Charta', 'depto_id' => 68],
            ['id' => 190, 'ciudad' => 'Chigorodó', 'depto_id' => 5],
            ['id' => 191, 'ciudad' => 'Chima', 'depto_id' => 68],
            ['id' => 192, 'ciudad' => 'Chimichagua', 'depto_id' => 20],
            ['id' => 193, 'ciudad' => 'Chimá', 'depto_id' => 23],
            ['id' => 194, 'ciudad' => 'Chinavita', 'depto_id' => 15],
            ['id' => 195, 'ciudad' => 'Chinchiná', 'depto_id' => 17],
            ['id' => 196, 'ciudad' => 'Chinácota', 'depto_id' => 54],
            ['id' => 197, 'ciudad' => 'Chinú', 'depto_id' => 23],
            ['id' => 198, 'ciudad' => 'Chipaque', 'depto_id' => 25],
            ['id' => 199, 'ciudad' => 'Chipatá', 'depto_id' => 68],
            ['id' => 200, 'ciudad' => 'Chiquinquirá', 'depto_id' => 15],
            ['id' => 201, 'ciudad' => 'Chiriguaná', 'depto_id' => 20],
            ['id' => 202, 'ciudad' => 'Chiscas', 'depto_id' => 15],
            ['id' => 203, 'ciudad' => 'Chita', 'depto_id' => 15],
            ['id' => 204, 'ciudad' => 'Chitagá', 'depto_id' => 54],
            ['id' => 205, 'ciudad' => 'Chitaraque', 'depto_id' => 15],
            ['id' => 206, 'ciudad' => 'Chivatá', 'depto_id' => 15],
            ['id' => 207, 'ciudad' => 'Chivolo', 'depto_id' => 47],
            ['id' => 208, 'ciudad' => 'Choachí', 'depto_id' => 25],
            ['id' => 209, 'ciudad' => 'Chocontá', 'depto_id' => 25],
            ['id' => 210, 'ciudad' => 'Chámeza', 'depto_id' => 85],
            ['id' => 211, 'ciudad' => 'Chía', 'depto_id' => 25],
            ['id' => 212, 'ciudad' => 'Chíquiza', 'depto_id' => 15],
            ['id' => 213, 'ciudad' => 'Chívor', 'depto_id' => 15],
            ['id' => 214, 'ciudad' => 'Cicuco', 'depto_id' => 13],
            ['id' => 215, 'ciudad' => 'Cimitarra', 'depto_id' => 68],
            ['id' => 216, 'ciudad' => 'Circasia', 'depto_id' => 63],
            ['id' => 217, 'ciudad' => 'Cisneros', 'depto_id' => 5],
            ['id' => 218, 'ciudad' => 'Ciénaga', 'depto_id' => 15],
            ['id' => 219, 'ciudad' => 'Ciénaga', 'depto_id' => 47],
            ['id' => 220, 'ciudad' => 'Ciénaga de Oro', 'depto_id' => 23],
            ['id' => 221, 'ciudad' => 'Clemencia', 'depto_id' => 13],
            ['id' => 222, 'ciudad' => 'Cocorná', 'depto_id' => 5],
            ['id' => 223, 'ciudad' => 'Coello', 'depto_id' => 73],
            ['id' => 224, 'ciudad' => 'Cogua', 'depto_id' => 25],
            ['id' => 225, 'ciudad' => 'Colombia', 'depto_id' => 41],
            ['id' => 226, 'ciudad' => 'Colosó (Ricaurte)', 'depto_id' => 70],
            ['id' => 227, 'ciudad' => 'Colón', 'depto_id' => 86],
            ['id' => 228, 'ciudad' => 'Colón (Génova)', 'depto_id' => 52],
            ['id' => 229, 'ciudad' => 'Concepción', 'depto_id' => 5],
            ['id' => 230, 'ciudad' => 'Concepción', 'depto_id' => 68],
            ['id' => 231, 'ciudad' => 'Concordia', 'depto_id' => 5],
            ['id' => 232, 'ciudad' => 'Concordia', 'depto_id' => 47],
            ['id' => 233, 'ciudad' => 'Condoto', 'depto_id' => 27],
            ['id' => 234, 'ciudad' => 'Confines', 'depto_id' => 68],
            ['id' => 235, 'ciudad' => 'Consaca', 'depto_id' => 52],
            ['id' => 236, 'ciudad' => 'Contadero', 'depto_id' => 52],
            ['id' => 237, 'ciudad' => 'Contratación', 'depto_id' => 68],
            ['id' => 238, 'ciudad' => 'Convención', 'depto_id' => 54],
            ['id' => 239, 'ciudad' => 'Copacabana', 'depto_id' => 5],
            ['id' => 240, 'ciudad' => 'Coper', 'depto_id' => 15],
            ['id' => 241, 'ciudad' => 'Cordobá', 'depto_id' => 63],
            ['id' => 242, 'ciudad' => 'Corinto', 'depto_id' => 19],
            ['id' => 243, 'ciudad' => 'Coromoro', 'depto_id' => 68],
            ['id' => 244, 'ciudad' => 'Corozal', 'depto_id' => 70],
            ['id' => 245, 'ciudad' => 'Corrales', 'depto_id' => 15],
            ['id' => 246, 'ciudad' => 'Cota', 'depto_id' => 25],
            ['id' => 247, 'ciudad' => 'Cotorra', 'depto_id' => 23],
            ['id' => 248, 'ciudad' => 'Covarachía', 'depto_id' => 15],
            ['id' => 249, 'ciudad' => 'Coveñas', 'depto_id' => 70],
            ['id' => 250, 'ciudad' => 'Coyaima', 'depto_id' => 73],
            ['id' => 251, 'ciudad' => 'Cravo Norte', 'depto_id' => 81],
            ['id' => 252, 'ciudad' => 'Cuaspud (Carlosama)', 'depto_id' => 52],
            ['id' => 253, 'ciudad' => 'Cubarral', 'depto_id' => 50],
            ['id' => 254, 'ciudad' => 'Cubará', 'depto_id' => 15],
            ['id' => 255, 'ciudad' => 'Cucaita', 'depto_id' => 15],
            ['id' => 256, 'ciudad' => 'Cucunubá', 'depto_id' => 25],
            ['id' => 257, 'ciudad' => 'Cucutilla', 'depto_id' => 54],
            ['id' => 258, 'ciudad' => 'Cuitiva', 'depto_id' => 15],
            ['id' => 259, 'ciudad' => 'Cumaral', 'depto_id' => 50],
            ['id' => 260, 'ciudad' => 'Cumaribo', 'depto_id' => 99],
            ['id' => 261, 'ciudad' => 'Cumbal', 'depto_id' => 52],
            ['id' => 262, 'ciudad' => 'Cumbitara', 'depto_id' => 52],
            ['id' => 263, 'ciudad' => 'Cunday', 'depto_id' => 73],
            ['id' => 264, 'ciudad' => 'Curillo', 'depto_id' => 18],
            ['id' => 265, 'ciudad' => 'Curití', 'depto_id' => 68],
            ['id' => 266, 'ciudad' => 'Curumaní', 'depto_id' => 20],
            ['id' => 267, 'ciudad' => 'Cáceres', 'depto_id' => 5],
            ['id' => 268, 'ciudad' => 'Cáchira', 'depto_id' => 54],
            ['id' => 269, 'ciudad' => 'Cácota', 'depto_id' => 54],
            ['id' => 270, 'ciudad' => 'Cáqueza', 'depto_id' => 25],
            ['id' => 271, 'ciudad' => 'Cértegui', 'depto_id' => 27],
            ['id' => 272, 'ciudad' => 'Cómbita', 'depto_id' => 15],
            ['id' => 273, 'ciudad' => 'Córdoba', 'depto_id' => 13],
            ['id' => 274, 'ciudad' => 'Córdoba', 'depto_id' => 52],
            ['id' => 275, 'ciudad' => 'Cúcuta', 'depto_id' => 54],
            ['id' => 276, 'ciudad' => 'Dabeiba', 'depto_id' => 5],
            ['id' => 277, 'ciudad' => 'Dagua', 'depto_id' => 76],
            ['id' => 278, 'ciudad' => 'Dibulla', 'depto_id' => 44],
            ['id' => 279, 'ciudad' => 'Distracción', 'depto_id' => 44],
            ['id' => 280, 'ciudad' => 'Dolores', 'depto_id' => 73],
            ['id' => 281, 'ciudad' => 'Don Matías', 'depto_id' => 5],
            ['id' => 282, 'ciudad' => 'Dos Quebradas', 'depto_id' => 66],
            ['id' => 283, 'ciudad' => 'Duitama', 'depto_id' => 15],
            ['id' => 284, 'ciudad' => 'Durania', 'depto_id' => 54],
            ['id' => 285, 'ciudad' => 'Ebéjico', 'depto_id' => 5],
            ['id' => 286, 'ciudad' => 'El Bagre', 'depto_id' => 5],
            ['id' => 287, 'ciudad' => 'El Banco', 'depto_id' => 47],
            ['id' => 288, 'ciudad' => 'El Cairo', 'depto_id' => 76],
            ['id' => 289, 'ciudad' => 'El Calvario', 'depto_id' => 50],
            ['id' => 290, 'ciudad' => 'El Carmen', 'depto_id' => 54],
            ['id' => 291, 'ciudad' => 'El Carmen', 'depto_id' => 68],
            ['id' => 292, 'ciudad' => 'El Carmen de Atrato', 'depto_id' => 27],
            ['id' => 293, 'ciudad' => 'El Carmen de Bolívar', 'depto_id' => 13],
            ['id' => 294, 'ciudad' => 'El Castillo', 'depto_id' => 50],
            ['id' => 295, 'ciudad' => 'El Cerrito', 'depto_id' => 76],
            ['id' => 296, 'ciudad' => 'El Charco', 'depto_id' => 52],
            ['id' => 297, 'ciudad' => 'El Cocuy', 'depto_id' => 15],
            ['id' => 298, 'ciudad' => 'El Colegio', 'depto_id' => 25],
            ['id' => 299, 'ciudad' => 'El Copey', 'depto_id' => 20],
            ['id' => 300, 'ciudad' => 'El Doncello', 'depto_id' => 18],
            ['id' => 301, 'ciudad' => 'El Dorado', 'depto_id' => 50],
            ['id' => 302, 'ciudad' => 'El Dovio', 'depto_id' => 76],
            ['id' => 303, 'ciudad' => 'El Espino', 'depto_id' => 15],
            ['id' => 304, 'ciudad' => 'El Guacamayo', 'depto_id' => 68],
            ['id' => 305, 'ciudad' => 'El Guamo', 'depto_id' => 13],
            ['id' => 306, 'ciudad' => 'El Molino', 'depto_id' => 44],
            ['id' => 307, 'ciudad' => 'El Paso', 'depto_id' => 20],
            ['id' => 308, 'ciudad' => 'El Paujil', 'depto_id' => 18],
            ['id' => 309, 'ciudad' => 'El Peñol', 'depto_id' => 52],
            ['id' => 310, 'ciudad' => 'El Peñon', 'depto_id' => 13],
            ['id' => 311, 'ciudad' => 'El Peñon', 'depto_id' => 68],
            ['id' => 312, 'ciudad' => 'El Peñón', 'depto_id' => 25],
            ['id' => 313, 'ciudad' => 'El Piñon', 'depto_id' => 47],
            ['id' => 314, 'ciudad' => 'El Playón', 'depto_id' => 68],
            ['id' => 315, 'ciudad' => 'El Retorno', 'depto_id' => 95],
            ['id' => 316, 'ciudad' => 'El Retén', 'depto_id' => 47],
            ['id' => 317, 'ciudad' => 'El Roble', 'depto_id' => 70],
            ['id' => 318, 'ciudad' => 'El Rosal', 'depto_id' => 25],
            ['id' => 319, 'ciudad' => 'El Rosario', 'depto_id' => 52],
            ['id' => 320, 'ciudad' => 'El Tablón de Gómez', 'depto_id' => 52],
            ['id' => 321, 'ciudad' => 'El Tambo', 'depto_id' => 19],
            ['id' => 322, 'ciudad' => 'El Tambo', 'depto_id' => 52],
            ['id' => 323, 'ciudad' => 'El Tarra', 'depto_id' => 54],
            ['id' => 324, 'ciudad' => 'El Zulia', 'depto_id' => 54],
            ['id' => 325, 'ciudad' => 'El Águila', 'depto_id' => 76],
            ['id' => 326, 'ciudad' => 'Elías', 'depto_id' => 41],
            ['id' => 327, 'ciudad' => 'Encino', 'depto_id' => 68],
            ['id' => 328, 'ciudad' => 'Enciso', 'depto_id' => 68],
            ['id' => 329, 'ciudad' => 'Entrerríos', 'depto_id' => 5],
            ['id' => 330, 'ciudad' => 'Envigado', 'depto_id' => 5],
            ['id' => 331, 'ciudad' => 'Espinal', 'depto_id' => 73],
            ['id' => 332, 'ciudad' => 'Facatativá', 'depto_id' => 25],
            ['id' => 333, 'ciudad' => 'Falan', 'depto_id' => 73],
            ['id' => 334, 'ciudad' => 'Filadelfia', 'depto_id' => 17],
            ['id' => 335, 'ciudad' => 'Filandia', 'depto_id' => 63],
            ['id' => 336, 'ciudad' => 'Firavitoba', 'depto_id' => 15],
            ['id' => 337, 'ciudad' => 'Flandes', 'depto_id' => 73],
            ['id' => 338, 'ciudad' => 'Florencia', 'depto_id' => 18],
            ['id' => 339, 'ciudad' => 'Florencia', 'depto_id' => 19],
            ['id' => 340, 'ciudad' => 'Floresta', 'depto_id' => 15],
            ['id' => 341, 'ciudad' => 'Florida', 'depto_id' => 76],
            ['id' => 342, 'ciudad' => 'Floridablanca', 'depto_id' => 68],
            ['id' => 343, 'ciudad' => 'Florián', 'depto_id' => 68],
            ['id' => 344, 'ciudad' => 'Fonseca', 'depto_id' => 44],
            ['id' => 345, 'ciudad' => 'Fortúl', 'depto_id' => 81],
            ['id' => 346, 'ciudad' => 'Fosca', 'depto_id' => 25],
            ['id' => 347, 'ciudad' => 'Francisco Pizarro', 'depto_id' => 52],
            ['id' => 348, 'ciudad' => 'Fredonia', 'depto_id' => 5],
            ['id' => 349, 'ciudad' => 'Fresno', 'depto_id' => 73],
            ['id' => 350, 'ciudad' => 'Frontino', 'depto_id' => 5],
            ['id' => 351, 'ciudad' => 'Fuente de Oro', 'depto_id' => 50],
            ['id' => 352, 'ciudad' => 'Fundación', 'depto_id' => 47],
            ['id' => 353, 'ciudad' => 'Funes', 'depto_id' => 52],
            ['id' => 354, 'ciudad' => 'Funza', 'depto_id' => 25],
            ['id' => 355, 'ciudad' => 'Fusagasugá', 'depto_id' => 25],
            ['id' => 356, 'ciudad' => 'Fómeque', 'depto_id' => 25],
            ['id' => 357, 'ciudad' => 'Fúquene', 'depto_id' => 25],
            ['id' => 358, 'ciudad' => 'Gachalá', 'depto_id' => 25],
            ['id' => 359, 'ciudad' => 'Gachancipá', 'depto_id' => 25],
            ['id' => 360, 'ciudad' => 'Gachantivá', 'depto_id' => 15],
            ['id' => 361, 'ciudad' => 'Gachetá', 'depto_id' => 25],
            ['id' => 362, 'ciudad' => 'Galapa', 'depto_id' => 8],
            ['id' => 363, 'ciudad' => 'Galeras (Nueva Granada)', 'depto_id' => 70],
            ['id' => 364, 'ciudad' => 'Galán', 'depto_id' => 68],
            ['id' => 365, 'ciudad' => 'Gama', 'depto_id' => 25],
            ['id' => 366, 'ciudad' => 'Gamarra', 'depto_id' => 20],
            ['id' => 367, 'ciudad' => 'Garagoa', 'depto_id' => 15],
            ['id' => 368, 'ciudad' => 'Garzón', 'depto_id' => 41],
            ['id' => 369, 'ciudad' => 'Gigante', 'depto_id' => 41],
            ['id' => 370, 'ciudad' => 'Ginebra', 'depto_id' => 76],
            ['id' => 371, 'ciudad' => 'Giraldo', 'depto_id' => 5],
            ['id' => 372, 'ciudad' => 'Girardot', 'depto_id' => 25],
            ['id' => 373, 'ciudad' => 'Girardota', 'depto_id' => 5],
            ['id' => 374, 'ciudad' => 'Girón', 'depto_id' => 68],
            ['id' => 375, 'ciudad' => 'Gonzalez', 'depto_id' => 20],
            ['id' => 376, 'ciudad' => 'Gramalote', 'depto_id' => 54],
            ['id' => 377, 'ciudad' => 'Granada', 'depto_id' => 5],
            ['id' => 378, 'ciudad' => 'Granada', 'depto_id' => 25],
            ['id' => 379, 'ciudad' => 'Granada', 'depto_id' => 50],
            ['id' => 380, 'ciudad' => 'Guaca', 'depto_id' => 68],
            ['id' => 381, 'ciudad' => 'Guacamayas', 'depto_id' => 15],
            ['id' => 382, 'ciudad' => 'Guacarí', 'depto_id' => 76],
            ['id' => 383, 'ciudad' => 'Guachavés', 'depto_id' => 52],
            ['id' => 384, 'ciudad' => 'Guachené', 'depto_id' => 19],
            ['id' => 385, 'ciudad' => 'Guachetá', 'depto_id' => 25],
            ['id' => 386, 'ciudad' => 'Guachucal', 'depto_id' => 52],
            ['id' => 387, 'ciudad' => 'Guadalupe', 'depto_id' => 5],
            ['id' => 388, 'ciudad' => 'Guadalupe', 'depto_id' => 41],
            ['id' => 389, 'ciudad' => 'Guadalupe', 'depto_id' => 68],
            ['id' => 390, 'ciudad' => 'Guaduas', 'depto_id' => 25],
            ['id' => 391, 'ciudad' => 'Guaitarilla', 'depto_id' => 52],
            ['id' => 392, 'ciudad' => 'Gualmatán', 'depto_id' => 52],
            ['id' => 393, 'ciudad' => 'Guamal', 'depto_id' => 47],
            ['id' => 394, 'ciudad' => 'Guamal', 'depto_id' => 50],
            ['id' => 395, 'ciudad' => 'Guamo', 'depto_id' => 73],
            ['id' => 396, 'ciudad' => 'Guapota', 'depto_id' => 68],
            ['id' => 397, 'ciudad' => 'Guapí', 'depto_id' => 19],
            ['id' => 398, 'ciudad' => 'Guaranda', 'depto_id' => 70],
            ['id' => 399, 'ciudad' => 'Guarne', 'depto_id' => 5],
            ['id' => 400, 'ciudad' => 'Guasca', 'depto_id' => 25],
            ['id' => 401, 'ciudad' => 'Guatapé', 'depto_id' => 5],
            ['id' => 402, 'ciudad' => 'Guataquí', 'depto_id' => 25],
            ['id' => 403, 'ciudad' => 'Guatavita', 'depto_id' => 25],
            ['id' => 404, 'ciudad' => 'Guateque', 'depto_id' => 15],
            ['id' => 405, 'ciudad' => 'Guavatá', 'depto_id' => 68],
            ['id' => 406, 'ciudad' => 'Guayabal de Siquima', 'depto_id' => 25],
            ['id' => 407, 'ciudad' => 'Guayabetal', 'depto_id' => 25],
            ['id' => 408, 'ciudad' => 'Guayatá', 'depto_id' => 15],
            ['id' => 409, 'ciudad' => 'Guepsa', 'depto_id' => 68],
            ['id' => 410, 'ciudad' => 'Guicán', 'depto_id' => 15],
            ['id' => 411, 'ciudad' => 'Gutiérrez', 'depto_id' => 25],
            ['id' => 412, 'ciudad' => 'Guática', 'depto_id' => 66],
            ['id' => 413, 'ciudad' => 'Gámbita', 'depto_id' => 68],
            ['id' => 414, 'ciudad' => 'Gámeza', 'depto_id' => 15],
            ['id' => 415, 'ciudad' => 'Génova', 'depto_id' => 63],
            ['id' => 416, 'ciudad' => 'Gómez Plata', 'depto_id' => 5],
            ['id' => 417, 'ciudad' => 'Hacarí', 'depto_id' => 54],
            ['id' => 418, 'ciudad' => 'Hatillo de Loba', 'depto_id' => 13],
            ['id' => 419, 'ciudad' => 'Hato', 'depto_id' => 68],
            ['id' => 420, 'ciudad' => 'Hato Corozal', 'depto_id' => 85],
            ['id' => 421, 'ciudad' => 'Hatonuevo', 'depto_id' => 44],
            ['id' => 422, 'ciudad' => 'Heliconia', 'depto_id' => 5],
            ['id' => 423, 'ciudad' => 'Herrán', 'depto_id' => 54],
            ['id' => 424, 'ciudad' => 'Herveo', 'depto_id' => 73],
            ['id' => 425, 'ciudad' => 'Hispania', 'depto_id' => 5],
            ['id' => 426, 'ciudad' => 'Hobo', 'depto_id' => 41],
            ['id' => 427, 'ciudad' => 'Honda', 'depto_id' => 73],
            ['id' => 428, 'ciudad' => 'Ibagué', 'depto_id' => 73],
            ['id' => 429, 'ciudad' => 'Icononzo', 'depto_id' => 73],
            ['id' => 430, 'ciudad' => 'Iles', 'depto_id' => 52],
            ['id' => 431, 'ciudad' => 'Imúes', 'depto_id' => 52],
            ['id' => 432, 'ciudad' => 'Inzá', 'depto_id' => 19],
            ['id' => 433, 'ciudad' => 'Inírida', 'depto_id' => 94],
            ['id' => 434, 'ciudad' => 'Ipiales', 'depto_id' => 52],
            ['id' => 435, 'ciudad' => 'Isnos', 'depto_id' => 41],
            ['id' => 436, 'ciudad' => 'Istmina', 'depto_id' => 27],
            ['id' => 437, 'ciudad' => 'Itagüí', 'depto_id' => 5],
            ['id' => 438, 'ciudad' => 'Ituango', 'depto_id' => 5],
            ['id' => 439, 'ciudad' => 'Izá', 'depto_id' => 15],
            ['id' => 440, 'ciudad' => 'Jambaló', 'depto_id' => 19],
            ['id' => 441, 'ciudad' => 'Jamundí', 'depto_id' => 76],
            ['id' => 442, 'ciudad' => 'Jardín', 'depto_id' => 5],
            ['id' => 443, 'ciudad' => 'Jenesano', 'depto_id' => 15],
            ['id' => 444, 'ciudad' => 'Jericó', 'depto_id' => 5],
            ['id' => 445, 'ciudad' => 'Jericó', 'depto_id' => 15],
            ['id' => 446, 'ciudad' => 'Jerusalén', 'depto_id' => 25],
            ['id' => 447, 'ciudad' => 'Jesús María', 'depto_id' => 68],
            ['id' => 448, 'ciudad' => 'Jordán', 'depto_id' => 68],
            ['id' => 449, 'ciudad' => 'Juan de Acosta', 'depto_id' => 8],
            ['id' => 450, 'ciudad' => 'Junín', 'depto_id' => 25],
            ['id' => 451, 'ciudad' => 'Juradó', 'depto_id' => 27],
            ['id' => 452, 'ciudad' => 'La Apartada y La Frontera', 'depto_id' => 23],
            ['id' => 453, 'ciudad' => 'La Argentina', 'depto_id' => 41],
            ['id' => 454, 'ciudad' => 'La Belleza', 'depto_id' => 68],
            ['id' => 455, 'ciudad' => 'La Calera', 'depto_id' => 25],
            ['id' => 456, 'ciudad' => 'La Capilla', 'depto_id' => 15],
            ['id' => 457, 'ciudad' => 'La Ceja', 'depto_id' => 5],
            ['id' => 458, 'ciudad' => 'La Celia', 'depto_id' => 66],
            ['id' => 459, 'ciudad' => 'La Cruz', 'depto_id' => 52],
            ['id' => 460, 'ciudad' => 'La Cumbre', 'depto_id' => 76],
            ['id' => 461, 'ciudad' => 'La Dorada', 'depto_id' => 17],
            ['id' => 462, 'ciudad' => 'La Esperanza', 'depto_id' => 54],
            ['id' => 463, 'ciudad' => 'La Estrella', 'depto_id' => 5],
            ['id' => 464, 'ciudad' => 'La Florida', 'depto_id' => 52],
            ['id' => 465, 'ciudad' => 'La Gloria', 'depto_id' => 20],
            ['id' => 466, 'ciudad' => 'La Jagua de Ibirico', 'depto_id' => 20],
            ['id' => 467, 'ciudad' => 'La Jagua del Pilar', 'depto_id' => 44],
            ['id' => 468, 'ciudad' => 'La Llanada', 'depto_id' => 52],
            ['id' => 469, 'ciudad' => 'La Macarena', 'depto_id' => 50],
            ['id' => 470, 'ciudad' => 'La Merced', 'depto_id' => 17],
            ['id' => 471, 'ciudad' => 'La Mesa', 'depto_id' => 25],
            ['id' => 472, 'ciudad' => 'La Montañita', 'depto_id' => 18],
            ['id' => 473, 'ciudad' => 'La Palma', 'depto_id' => 25],
            ['id' => 474, 'ciudad' => 'La Paz', 'depto_id' => 68],
            ['id' => 475, 'ciudad' => 'La Paz (Robles)', 'depto_id' => 20],
            ['id' => 476, 'ciudad' => 'La Peña', 'depto_id' => 25],
            ['id' => 477, 'ciudad' => 'La Pintada', 'depto_id' => 5],
            ['id' => 478, 'ciudad' => 'La Plata', 'depto_id' => 41],
            ['id' => 479, 'ciudad' => 'La Playa', 'depto_id' => 54],
            ['id' => 480, 'ciudad' => 'La Primavera', 'depto_id' => 99],
            ['id' => 481, 'ciudad' => 'La Salina', 'depto_id' => 85],
            ['id' => 482, 'ciudad' => 'La Sierra', 'depto_id' => 19],
            ['id' => 483, 'ciudad' => 'La Tebaida', 'depto_id' => 63],
            ['id' => 484, 'ciudad' => 'La Tola', 'depto_id' => 52],
            ['id' => 485, 'ciudad' => 'La Unión', 'depto_id' => 5],
            ['id' => 486, 'ciudad' => 'La Unión', 'depto_id' => 52],
            ['id' => 487, 'ciudad' => 'La Unión', 'depto_id' => 70],
            ['id' => 488, 'ciudad' => 'La Unión', 'depto_id' => 76],
            ['id' => 489, 'ciudad' => 'La Uvita', 'depto_id' => 15],
            ['id' => 490, 'ciudad' => 'La Vega', 'depto_id' => 19],
            ['id' => 491, 'ciudad' => 'La Vega', 'depto_id' => 25],
            ['id' => 492, 'ciudad' => 'La Victoria', 'depto_id' => 15],
            ['id' => 493, 'ciudad' => 'La Victoria', 'depto_id' => 17],
            ['id' => 494, 'ciudad' => 'La Victoria', 'depto_id' => 76],
            ['id' => 495, 'ciudad' => 'La Virginia', 'depto_id' => 66],
            ['id' => 496, 'ciudad' => 'Labateca', 'depto_id' => 54],
            ['id' => 497, 'ciudad' => 'Labranzagrande', 'depto_id' => 15],
            ['id' => 498, 'ciudad' => 'Landázuri', 'depto_id' => 68],
            ['id' => 499, 'ciudad' => 'Lebrija', 'depto_id' => 68],
            ['id' => 500, 'ciudad' => 'Leiva', 'depto_id' => 52],
            ['id' => 501, 'ciudad' => 'Lejanías', 'depto_id' => 50],
            ['id' => 502, 'ciudad' => 'Lenguazaque', 'depto_id' => 25],
            ['id' => 503, 'ciudad' => 'Leticia', 'depto_id' => 91],
            ['id' => 504, 'ciudad' => 'Liborina', 'depto_id' => 5],
            ['id' => 505, 'ciudad' => 'Linares', 'depto_id' => 52],
            ['id' => 506, 'ciudad' => 'Lloró', 'depto_id' => 27],
            ['id' => 507, 'ciudad' => 'Lorica', 'depto_id' => 23],
            ['id' => 508, 'ciudad' => 'Los Córdobas', 'depto_id' => 23],
            ['id' => 509, 'ciudad' => 'Los Palmitos', 'depto_id' => 70],
            ['id' => 510, 'ciudad' => 'Los Patios', 'depto_id' => 54],
            ['id' => 511, 'ciudad' => 'Los Santos', 'depto_id' => 68],
            ['id' => 512, 'ciudad' => 'Lourdes', 'depto_id' => 54],
            ['id' => 513, 'ciudad' => 'Luruaco', 'depto_id' => 8],
            ['id' => 514, 'ciudad' => 'Lérida', 'depto_id' => 73],
            ['id' => 515, 'ciudad' => 'Líbano', 'depto_id' => 73],
            ['id' => 516, 'ciudad' => 'López (Micay)', 'depto_id' => 19],
            ['id' => 517, 'ciudad' => 'Macanal', 'depto_id' => 15],
            ['id' => 518, 'ciudad' => 'Macaravita', 'depto_id' => 68],
            ['id' => 519, 'ciudad' => 'Maceo', 'depto_id' => 5],
            ['id' => 520, 'ciudad' => 'Machetá', 'depto_id' => 25],
            ['id' => 521, 'ciudad' => 'Madrid', 'depto_id' => 25],
            ['id' => 522, 'ciudad' => 'Magangué', 'depto_id' => 13],
            ['id' => 523, 'ciudad' => 'Magüi (Payán)', 'depto_id' => 52],
            ['id' => 524, 'ciudad' => 'Mahates', 'depto_id' => 13],
            ['id' => 525, 'ciudad' => 'Maicao', 'depto_id' => 44],
            ['id' => 526, 'ciudad' => 'Majagual', 'depto_id' => 70],
            ['id' => 527, 'ciudad' => 'Malambo', 'depto_id' => 8],
            ['id' => 528, 'ciudad' => 'Mallama (Piedrancha)', 'depto_id' => 52],
            ['id' => 529, 'ciudad' => 'Manatí', 'depto_id' => 8],
            ['id' => 530, 'ciudad' => 'Manaure', 'depto_id' => 44],
            ['id' => 531, 'ciudad' => 'Manaure Balcón del Cesar', 'depto_id' => 20],
            ['id' => 532, 'ciudad' => 'Manizales', 'depto_id' => 17],
            ['id' => 533, 'ciudad' => 'Manta', 'depto_id' => 25],
            ['id' => 534, 'ciudad' => 'Manzanares', 'depto_id' => 17],
            ['id' => 535, 'ciudad' => 'Maní', 'depto_id' => 85],
            ['id' => 536, 'ciudad' => 'Mapiripan', 'depto_id' => 50],
            ['id' => 537, 'ciudad' => 'Margarita', 'depto_id' => 13],
            ['id' => 538, 'ciudad' => 'Marinilla', 'depto_id' => 5],
            ['id' => 539, 'ciudad' => 'Maripí', 'depto_id' => 15],
            ['id' => 540, 'ciudad' => 'Mariquita', 'depto_id' => 73],
            ['id' => 541, 'ciudad' => 'Marmato', 'depto_id' => 17],
            ['id' => 542, 'ciudad' => 'Marquetalia', 'depto_id' => 17],
            ['id' => 543, 'ciudad' => 'Marsella', 'depto_id' => 66],
            ['id' => 544, 'ciudad' => 'Marulanda', 'depto_id' => 17],
            ['id' => 545, 'ciudad' => 'María la Baja', 'depto_id' => 13],
            ['id' => 546, 'ciudad' => 'Matanza', 'depto_id' => 68],
            ['id' => 547, 'ciudad' => 'Medellín', 'depto_id' => 5],
            ['id' => 548, 'ciudad' => 'Medina', 'depto_id' => 25],
            ['id' => 549, 'ciudad' => 'Medio Atrato', 'depto_id' => 27],
            ['id' => 550, 'ciudad' => 'Medio Baudó', 'depto_id' => 27],
            ['id' => 551, 'ciudad' => 'Medio San Juan (ANDAGOYA)', 'depto_id' => 27],
            ['id' => 552, 'ciudad' => 'Melgar', 'depto_id' => 73],
            ['id' => 553, 'ciudad' => 'Mercaderes', 'depto_id' => 19],
            ['id' => 554, 'ciudad' => 'Mesetas', 'depto_id' => 50],
            ['id' => 555, 'ciudad' => 'Milán', 'depto_id' => 18],
            ['id' => 556, 'ciudad' => 'Miraflores', 'depto_id' => 15],
            ['id' => 557, 'ciudad' => 'Miraflores', 'depto_id' => 95],
            ['id' => 558, 'ciudad' => 'Miranda', 'depto_id' => 19],
            ['id' => 559, 'ciudad' => 'Mistrató', 'depto_id' => 66],
            ['id' => 560, 'ciudad' => 'Mitú', 'depto_id' => 97],
            ['id' => 561, 'ciudad' => 'Mocoa', 'depto_id' => 86],
            ['id' => 562, 'ciudad' => 'Mogotes', 'depto_id' => 68],
            ['id' => 563, 'ciudad' => 'Molagavita', 'depto_id' => 68],
            ['id' => 564, 'ciudad' => 'Momil', 'depto_id' => 23],
            ['id' => 565, 'ciudad' => 'Mompós', 'depto_id' => 13],
            ['id' => 566, 'ciudad' => 'Mongua', 'depto_id' => 15],
            ['id' => 567, 'ciudad' => 'Monguí', 'depto_id' => 15],
            ['id' => 568, 'ciudad' => 'Moniquirá', 'depto_id' => 15],
            ['id' => 569, 'ciudad' => 'Montebello', 'depto_id' => 5],
            ['id' => 570, 'ciudad' => 'Montecristo', 'depto_id' => 13],
            ['id' => 571, 'ciudad' => 'Montelíbano', 'depto_id' => 23],
            ['id' => 572, 'ciudad' => 'Montenegro', 'depto_id' => 63],
            ['id' => 573, 'ciudad' => 'Monteria', 'depto_id' => 23],
            ['id' => 574, 'ciudad' => 'Monterrey', 'depto_id' => 85],
            ['id' => 575, 'ciudad' => 'Morales', 'depto_id' => 13],
            ['id' => 576, 'ciudad' => 'Morales', 'depto_id' => 19],
            ['id' => 577, 'ciudad' => 'Morelia', 'depto_id' => 18],
            ['id' => 578, 'ciudad' => 'Morroa', 'depto_id' => 70],
            ['id' => 579, 'ciudad' => 'Mosquera', 'depto_id' => 25],
            ['id' => 580, 'ciudad' => 'Mosquera', 'depto_id' => 52],
            ['id' => 581, 'ciudad' => 'Motavita', 'depto_id' => 15],
            ['id' => 582, 'ciudad' => 'Moñitos', 'depto_id' => 23],
            ['id' => 583, 'ciudad' => 'Murillo', 'depto_id' => 73],
            ['id' => 584, 'ciudad' => 'Murindó', 'depto_id' => 5],
            ['id' => 585, 'ciudad' => 'Mutatá', 'depto_id' => 5],
            ['id' => 586, 'ciudad' => 'Mutiscua', 'depto_id' => 54],
            ['id' => 587, 'ciudad' => 'Muzo', 'depto_id' => 15],
            ['id' => 588, 'ciudad' => 'Málaga', 'depto_id' => 68],
            ['id' => 589, 'ciudad' => 'Nariño', 'depto_id' => 5],
            ['id' => 590, 'ciudad' => 'Nariño', 'depto_id' => 25],
            ['id' => 591, 'ciudad' => 'Nariño', 'depto_id' => 52],
            ['id' => 592, 'ciudad' => 'Natagaima', 'depto_id' => 73],
            ['id' => 593, 'ciudad' => 'Nechí', 'depto_id' => 5],
            ['id' => 594, 'ciudad' => 'Necoclí', 'depto_id' => 5],
            ['id' => 595, 'ciudad' => 'Neira', 'depto_id' => 17],
            ['id' => 596, 'ciudad' => 'Neiva', 'depto_id' => 41],
            ['id' => 597, 'ciudad' => 'Nemocón', 'depto_id' => 25],
            ['id' => 598, 'ciudad' => 'Nilo', 'depto_id' => 25],
            ['id' => 599, 'ciudad' => 'Nimaima', 'depto_id' => 25],
            ['id' => 600, 'ciudad' => 'Nobsa', 'depto_id' => 15],
            ['id' => 601, 'ciudad' => 'Nocaima', 'depto_id' => 25],
            ['id' => 602, 'ciudad' => 'Norcasia', 'depto_id' => 17],
            ['id' => 603, 'ciudad' => 'Norosí', 'depto_id' => 13],
            ['id' => 604, 'ciudad' => 'Novita', 'depto_id' => 27],
            ['id' => 605, 'ciudad' => 'Nueva Granada', 'depto_id' => 47],
            ['id' => 606, 'ciudad' => 'Nuevo Colón', 'depto_id' => 15],
            ['id' => 607, 'ciudad' => 'Nunchía', 'depto_id' => 85],
            ['id' => 608, 'ciudad' => 'Nuquí', 'depto_id' => 27],
            ['id' => 609, 'ciudad' => 'Nátaga', 'depto_id' => 41],
            ['id' => 610, 'ciudad' => 'Obando', 'depto_id' => 76],
            ['id' => 611, 'ciudad' => 'Ocamonte', 'depto_id' => 68],
            ['id' => 612, 'ciudad' => 'Ocaña', 'depto_id' => 54],
            ['id' => 613, 'ciudad' => 'Oiba', 'depto_id' => 68],
            ['id' => 614, 'ciudad' => 'Oicatá', 'depto_id' => 15],
            ['id' => 615, 'ciudad' => 'Olaya', 'depto_id' => 5],
            ['id' => 616, 'ciudad' => 'Olaya Herrera', 'depto_id' => 52],
            ['id' => 617, 'ciudad' => 'Onzaga', 'depto_id' => 68],
            ['id' => 618, 'ciudad' => 'Oporapa', 'depto_id' => 41],
            ['id' => 619, 'ciudad' => 'Orito', 'depto_id' => 86],
            ['id' => 620, 'ciudad' => 'Orocué', 'depto_id' => 85],
            ['id' => 621, 'ciudad' => 'Ortega', 'depto_id' => 73],
            ['id' => 622, 'ciudad' => 'Ospina', 'depto_id' => 52],
            ['id' => 623, 'ciudad' => 'Otanche', 'depto_id' => 15],
            ['id' => 624, 'ciudad' => 'Ovejas', 'depto_id' => 70],
            ['id' => 625, 'ciudad' => 'Pachavita', 'depto_id' => 15],
            ['id' => 626, 'ciudad' => 'Pacho', 'depto_id' => 25],
            ['id' => 627, 'ciudad' => 'Padilla', 'depto_id' => 19],
            ['id' => 628, 'ciudad' => 'Paicol', 'depto_id' => 41],
            ['id' => 629, 'ciudad' => 'Pailitas', 'depto_id' => 20],
            ['id' => 630, 'ciudad' => 'Paime', 'depto_id' => 25],
            ['id' => 631, 'ciudad' => 'Paipa', 'depto_id' => 15],
            ['id' => 632, 'ciudad' => 'Pajarito', 'depto_id' => 15],
            ['id' => 633, 'ciudad' => 'Palermo', 'depto_id' => 41],
            ['id' => 634, 'ciudad' => 'Palestina', 'depto_id' => 17],
            ['id' => 635, 'ciudad' => 'Palestina', 'depto_id' => 41],
            ['id' => 636, 'ciudad' => 'Palmar', 'depto_id' => 68],
            ['id' => 637, 'ciudad' => 'Palmar de Varela', 'depto_id' => 8],
            ['id' => 638, 'ciudad' => 'Palmas del Socorro', 'depto_id' => 68],
            ['id' => 639, 'ciudad' => 'Palmira', 'depto_id' => 76],
            ['id' => 640, 'ciudad' => 'Palmito', 'depto_id' => 70],
            ['id' => 641, 'ciudad' => 'Palocabildo', 'depto_id' => 73],
            ['id' => 642, 'ciudad' => 'Pamplona', 'depto_id' => 54],
            ['id' => 643, 'ciudad' => 'Pamplonita', 'depto_id' => 54],
            ['id' => 644, 'ciudad' => 'Pandi', 'depto_id' => 25],
            ['id' => 645, 'ciudad' => 'Panqueba', 'depto_id' => 15],
            ['id' => 646, 'ciudad' => 'Paratebueno', 'depto_id' => 25],
            ['id' => 647, 'ciudad' => 'Pasca', 'depto_id' => 25],
            ['id' => 648, 'ciudad' => 'Patía (El Bordo)', 'depto_id' => 19],
            ['id' => 649, 'ciudad' => 'Pauna', 'depto_id' => 15],
            ['id' => 650, 'ciudad' => 'Paya', 'depto_id' => 15],
            ['id' => 651, 'ciudad' => 'Paz de Ariporo', 'depto_id' => 85],
            ['id' => 652, 'ciudad' => 'Paz de Río', 'depto_id' => 15],
            ['id' => 653, 'ciudad' => 'Pedraza', 'depto_id' => 47],
            ['id' => 654, 'ciudad' => 'Pelaya', 'depto_id' => 20],
            ['id' => 655, 'ciudad' => 'Pensilvania', 'depto_id' => 17],
            ['id' => 656, 'ciudad' => 'Peque', 'depto_id' => 5],
            ['id' => 657, 'ciudad' => 'Pereira', 'depto_id' => 66],
            ['id' => 658, 'ciudad' => 'Pesca', 'depto_id' => 15],
            ['id' => 659, 'ciudad' => 'Peñol', 'depto_id' => 5],
            ['id' => 660, 'ciudad' => 'Piamonte', 'depto_id' => 19],
            ['id' => 661, 'ciudad' => 'Pie de Cuesta', 'depto_id' => 68],
            ['id' => 662, 'ciudad' => 'Piedras', 'depto_id' => 73],
            ['id' => 663, 'ciudad' => 'Piendamó', 'depto_id' => 19],
            ['id' => 664, 'ciudad' => 'Pijao', 'depto_id' => 63],
            ['id' => 665, 'ciudad' => 'Pijiño', 'depto_id' => 47],
            ['id' => 666, 'ciudad' => 'Pinchote', 'depto_id' => 68],
            ['id' => 667, 'ciudad' => 'Pinillos', 'depto_id' => 13],
            ['id' => 668, 'ciudad' => 'Piojo', 'depto_id' => 8],
            ['id' => 669, 'ciudad' => 'Pisva', 'depto_id' => 15],
            ['id' => 670, 'ciudad' => 'Pital', 'depto_id' => 41],
            ['id' => 671, 'ciudad' => 'Pitalito', 'depto_id' => 41],
            ['id' => 672, 'ciudad' => 'Pivijay', 'depto_id' => 47],
            ['id' => 673, 'ciudad' => 'Planadas', 'depto_id' => 73],
            ['id' => 674, 'ciudad' => 'Planeta Rica', 'depto_id' => 23],
            ['id' => 675, 'ciudad' => 'Plato', 'depto_id' => 47],
            ['id' => 676, 'ciudad' => 'Policarpa', 'depto_id' => 52],
            ['id' => 677, 'ciudad' => 'Polonuevo', 'depto_id' => 8],
            ['id' => 678, 'ciudad' => 'Ponedera', 'depto_id' => 8],
            ['id' => 679, 'ciudad' => 'Popayán', 'depto_id' => 19],
            ['id' => 680, 'ciudad' => 'Pore', 'depto_id' => 85],
            ['id' => 681, 'ciudad' => 'Potosí', 'depto_id' => 52],
            ['id' => 682, 'ciudad' => 'Pradera', 'depto_id' => 76],
            ['id' => 683, 'ciudad' => 'Prado', 'depto_id' => 73],
            ['id' => 684, 'ciudad' => 'Providencia', 'depto_id' => 52],
            ['id' => 685, 'ciudad' => 'Providencia', 'depto_id' => 88],
            ['id' => 686, 'ciudad' => 'Pueblo Bello', 'depto_id' => 20],
            ['id' => 687, 'ciudad' => 'Pueblo Nuevo', 'depto_id' => 23],
            ['id' => 688, 'ciudad' => 'Pueblo Rico', 'depto_id' => 66],
            ['id' => 689, 'ciudad' => 'Pueblorrico', 'depto_id' => 5],
            ['id' => 690, 'ciudad' => 'Puebloviejo', 'depto_id' => 47],
            ['id' => 691, 'ciudad' => 'Puente Nacional', 'depto_id' => 68],
            ['id' => 692, 'ciudad' => 'Puerres', 'depto_id' => 52],
            ['id' => 693, 'ciudad' => 'Puerto Asís', 'depto_id' => 86],
            ['id' => 694, 'ciudad' => 'Puerto Berrío', 'depto_id' => 5],
            ['id' => 695, 'ciudad' => 'Puerto Boyacá', 'depto_id' => 15],
            ['id' => 696, 'ciudad' => 'Puerto Caicedo', 'depto_id' => 86],
            ['id' => 697, 'ciudad' => 'Puerto Carreño', 'depto_id' => 99],
            ['id' => 698, 'ciudad' => 'Puerto Colombia', 'depto_id' => 8],
            ['id' => 699, 'ciudad' => 'Puerto Concordia', 'depto_id' => 50],
            ['id' => 700, 'ciudad' => 'Puerto Escondido', 'depto_id' => 23],
            ['id' => 701, 'ciudad' => 'Puerto Gaitán', 'depto_id' => 50],
            ['id' => 702, 'ciudad' => 'Puerto Guzmán', 'depto_id' => 86],
            ['id' => 703, 'ciudad' => 'Puerto Leguízamo', 'depto_id' => 86],
            ['id' => 704, 'ciudad' => 'Puerto Libertador', 'depto_id' => 23],
            ['id' => 705, 'ciudad' => 'Puerto Lleras', 'depto_id' => 50],
            ['id' => 706, 'ciudad' => 'Puerto López', 'depto_id' => 50],
            ['id' => 707, 'ciudad' => 'Puerto Nare', 'depto_id' => 5],
            ['id' => 708, 'ciudad' => 'Puerto Nariño', 'depto_id' => 91],
            ['id' => 709, 'ciudad' => 'Puerto Parra', 'depto_id' => 68],
            ['id' => 710, 'ciudad' => 'Puerto Rico', 'depto_id' => 18],
            ['id' => 711, 'ciudad' => 'Puerto Rico', 'depto_id' => 50],
            ['id' => 712, 'ciudad' => 'Puerto Rondón', 'depto_id' => 81],
            ['id' => 713, 'ciudad' => 'Puerto Salgar', 'depto_id' => 25],
            ['id' => 714, 'ciudad' => 'Puerto Santander', 'depto_id' => 54],
            ['id' => 715, 'ciudad' => 'Puerto Tejada', 'depto_id' => 19],
            ['id' => 716, 'ciudad' => 'Puerto Triunfo', 'depto_id' => 5],
            ['id' => 717, 'ciudad' => 'Puerto Wilches', 'depto_id' => 68],
            ['id' => 718, 'ciudad' => 'Pulí', 'depto_id' => 25],
            ['id' => 719, 'ciudad' => 'Pupiales', 'depto_id' => 52],
            ['id' => 720, 'ciudad' => 'Puracé (Coconuco)', 'depto_id' => 19],
            ['id' => 721, 'ciudad' => 'Purificación', 'depto_id' => 73],
            ['id' => 722, 'ciudad' => 'Purísima', 'depto_id' => 23],
            ['id' => 723, 'ciudad' => 'Pácora', 'depto_id' => 17],
            ['id' => 724, 'ciudad' => 'Páez', 'depto_id' => 15],
            ['id' => 725, 'ciudad' => 'Páez (Belalcazar)', 'depto_id' => 19],
            ['id' => 726, 'ciudad' => 'Páramo', 'depto_id' => 68],
            ['id' => 727, 'ciudad' => 'Quebradanegra', 'depto_id' => 25],
            ['id' => 728, 'ciudad' => 'Quetame', 'depto_id' => 25],
            ['id' => 729, 'ciudad' => 'Quibdó', 'depto_id' => 27],
            ['id' => 730, 'ciudad' => 'Quimbaya', 'depto_id' => 63],
            ['id' => 731, 'ciudad' => 'Quinchía', 'depto_id' => 66],
            ['id' => 732, 'ciudad' => 'Quipama', 'depto_id' => 15],
            ['id' => 733, 'ciudad' => 'Quipile', 'depto_id' => 25],
            ['id' => 734, 'ciudad' => 'Ragonvalia', 'depto_id' => 54],
            ['id' => 735, 'ciudad' => 'Ramiriquí', 'depto_id' => 15],
            ['id' => 736, 'ciudad' => 'Recetor', 'depto_id' => 85],
            ['id' => 737, 'ciudad' => 'Regidor', 'depto_id' => 13],
            ['id' => 738, 'ciudad' => 'Remedios', 'depto_id' => 5],
            ['id' => 739, 'ciudad' => 'Remolino', 'depto_id' => 47],
            ['id' => 740, 'ciudad' => 'Repelón', 'depto_id' => 8],
            ['id' => 741, 'ciudad' => 'Restrepo', 'depto_id' => 50],
            ['id' => 742, 'ciudad' => 'Restrepo', 'depto_id' => 76],
            ['id' => 743, 'ciudad' => 'Retiro', 'depto_id' => 5],
            ['id' => 744, 'ciudad' => 'Ricaurte', 'depto_id' => 25],
            ['id' => 745, 'ciudad' => 'Ricaurte', 'depto_id' => 52],
            ['id' => 746, 'ciudad' => 'Rio Negro', 'depto_id' => 68],
            ['id' => 747, 'ciudad' => 'Rioblanco', 'depto_id' => 73],
            ['id' => 748, 'ciudad' => 'Riofrío', 'depto_id' => 76],
            ['id' => 749, 'ciudad' => 'Riohacha', 'depto_id' => 44],
            ['id' => 750, 'ciudad' => 'Risaralda', 'depto_id' => 17],
            ['id' => 751, 'ciudad' => 'Rivera', 'depto_id' => 41],
            ['id' => 752, 'ciudad' => 'Roberto Payán (San José)', 'depto_id' => 52],
            ['id' => 753, 'ciudad' => 'Roldanillo', 'depto_id' => 76],
            ['id' => 754, 'ciudad' => 'Roncesvalles', 'depto_id' => 73],
            ['id' => 755, 'ciudad' => 'Rondón', 'depto_id' => 15],
            ['id' => 756, 'ciudad' => 'Rosas', 'depto_id' => 19],
            ['id' => 757, 'ciudad' => 'Rovira', 'depto_id' => 73],
            ['id' => 758, 'ciudad' => 'Ráquira', 'depto_id' => 15],
            ['id' => 759, 'ciudad' => 'Río Iró', 'depto_id' => 27],
            ['id' => 760, 'ciudad' => 'Río Quito', 'depto_id' => 27],
            ['id' => 761, 'ciudad' => 'Río Sucio', 'depto_id' => 17],
            ['id' => 762, 'ciudad' => 'Río Viejo', 'depto_id' => 13],
            ['id' => 763, 'ciudad' => 'Río de oro', 'depto_id' => 20],
            ['id' => 764, 'ciudad' => 'Ríonegro', 'depto_id' => 5],
            ['id' => 765, 'ciudad' => 'Ríosucio', 'depto_id' => 27],
            ['id' => 766, 'ciudad' => 'Sabana de Torres', 'depto_id' => 68],
            ['id' => 767, 'ciudad' => 'Sabanagrande', 'depto_id' => 8],
            ['id' => 768, 'ciudad' => 'Sabanalarga', 'depto_id' => 5],
            ['id' => 769, 'ciudad' => 'Sabanalarga', 'depto_id' => 8],
            ['id' => 770, 'ciudad' => 'Sabanalarga', 'depto_id' => 85],
            ['id' => 771, 'ciudad' => 'Sabanas de San Angel (SAN ANGEL)', 'depto_id' => 47],
            ['id' => 772, 'ciudad' => 'Sabaneta', 'depto_id' => 5],
            ['id' => 773, 'ciudad' => 'Saboyá', 'depto_id' => 15],
            ['id' => 774, 'ciudad' => 'Sahagún', 'depto_id' => 23],
            ['id' => 775, 'ciudad' => 'Saladoblanco', 'depto_id' => 41],
            ['id' => 776, 'ciudad' => 'Salamina', 'depto_id' => 17],
            ['id' => 777, 'ciudad' => 'Salamina', 'depto_id' => 47],
            ['id' => 778, 'ciudad' => 'Salazar', 'depto_id' => 54],
            ['id' => 779, 'ciudad' => 'Saldaña', 'depto_id' => 73],
            ['id' => 780, 'ciudad' => 'Salento', 'depto_id' => 63],
            ['id' => 781, 'ciudad' => 'Salgar', 'depto_id' => 5],
            ['id' => 782, 'ciudad' => 'Samacá', 'depto_id' => 15],
            ['id' => 783, 'ciudad' => 'Samaniego', 'depto_id' => 52],
            ['id' => 784, 'ciudad' => 'Samaná', 'depto_id' => 17],
            ['id' => 785, 'ciudad' => 'Sampués', 'depto_id' => 70],
            ['id' => 786, 'ciudad' => 'San Agustín', 'depto_id' => 41],
            ['id' => 787, 'ciudad' => 'San Alberto', 'depto_id' => 20],
            ['id' => 788, 'ciudad' => 'San Andrés', 'depto_id' => 68],
            ['id' => 789, 'ciudad' => 'San Andrés Sotavento', 'depto_id' => 23],
            ['id' => 790, 'ciudad' => 'San Andrés de Cuerquía', 'depto_id' => 5],
            ['id' => 791, 'ciudad' => 'San Antero', 'depto_id' => 23],
            ['id' => 792, 'ciudad' => 'San Antonio', 'depto_id' => 73],
            ['id' => 793, 'ciudad' => 'San Antonio de Tequendama', 'depto_id' => 25],
            ['id' => 794, 'ciudad' => 'San Benito', 'depto_id' => 68],
            ['id' => 795, 'ciudad' => 'San Benito Abad', 'depto_id' => 70],
            ['id' => 796, 'ciudad' => 'San Bernardo', 'depto_id' => 25],
            ['id' => 797, 'ciudad' => 'San Bernardo', 'depto_id' => 52],
            ['id' => 798, 'ciudad' => 'San Bernardo del Viento', 'depto_id' => 23],
            ['id' => 799, 'ciudad' => 'San Calixto', 'depto_id' => 54],
            ['id' => 800, 'ciudad' => 'San Carlos', 'depto_id' => 5],
            ['id' => 801, 'ciudad' => 'San Carlos', 'depto_id' => 23],
            ['id' => 802, 'ciudad' => 'San Carlos de Guaroa', 'depto_id' => 50],
            ['id' => 803, 'ciudad' => 'San Cayetano', 'depto_id' => 25],
            ['id' => 804, 'ciudad' => 'San Cayetano', 'depto_id' => 54],
            ['id' => 805, 'ciudad' => 'San Cristobal', 'depto_id' => 13],
            ['id' => 806, 'ciudad' => 'San Diego', 'depto_id' => 20],
            ['id' => 807, 'ciudad' => 'San Eduardo', 'depto_id' => 15],
            ['id' => 808, 'ciudad' => 'San Estanislao', 'depto_id' => 13],
            ['id' => 809, 'ciudad' => 'San Fernando', 'depto_id' => 13],
            ['id' => 810, 'ciudad' => 'San Francisco', 'depto_id' => 5],
            ['id' => 811, 'ciudad' => 'San Francisco', 'depto_id' => 25],
            ['id' => 812, 'ciudad' => 'San Francisco', 'depto_id' => 86],
            ['id' => 813, 'ciudad' => 'San Gíl', 'depto_id' => 68],
            ['id' => 814, 'ciudad' => 'San Jacinto', 'depto_id' => 13],
            ['id' => 815, 'ciudad' => 'San Jacinto del Cauca', 'depto_id' => 13],
            ['id' => 816, 'ciudad' => 'San Jerónimo', 'depto_id' => 5],
            ['id' => 817, 'ciudad' => 'San Joaquín', 'depto_id' => 68],
            ['id' => 818, 'ciudad' => 'San José', 'depto_id' => 17],
            ['id' => 819, 'ciudad' => 'San José de Miranda', 'depto_id' => 68],
            ['id' => 820, 'ciudad' => 'San José de Montaña', 'depto_id' => 5],
            ['id' => 821, 'ciudad' => 'San José de Pare', 'depto_id' => 15],
            ['id' => 822, 'ciudad' => 'San José de Uré', 'depto_id' => 23],
            ['id' => 823, 'ciudad' => 'San José del Fragua', 'depto_id' => 18],
            ['id' => 824, 'ciudad' => 'San José del Guaviare', 'depto_id' => 95],
            ['id' => 825, 'ciudad' => 'San José del Palmar', 'depto_id' => 27],
            ['id' => 826, 'ciudad' => 'San Juan de Arama', 'depto_id' => 50],
            ['id' => 827, 'ciudad' => 'San Juan de Betulia', 'depto_id' => 70],
            ['id' => 828, 'ciudad' => 'San Juan de Nepomuceno', 'depto_id' => 13],
            ['id' => 829, 'ciudad' => 'San Juan de Pasto', 'depto_id' => 52],
            ['id' => 830, 'ciudad' => 'San Juan de Río Seco', 'depto_id' => 25],
            ['id' => 831, 'ciudad' => 'San Juan de Urabá', 'depto_id' => 5],
            ['id' => 832, 'ciudad' => 'San Juan del Cesar', 'depto_id' => 44],
            ['id' => 833, 'ciudad' => 'San Juanito', 'depto_id' => 50],
            ['id' => 834, 'ciudad' => 'San Lorenzo', 'depto_id' => 52],
            ['id' => 835, 'ciudad' => 'San Luis', 'depto_id' => 73],
            ['id' => 836, 'ciudad' => 'San Luís', 'depto_id' => 5],
            ['id' => 837, 'ciudad' => 'San Luís de Gaceno', 'depto_id' => 15],
            ['id' => 838, 'ciudad' => 'San Luís de Palenque', 'depto_id' => 85],
            ['id' => 839, 'ciudad' => 'San Marcos', 'depto_id' => 70],
            ['id' => 840, 'ciudad' => 'San Martín', 'depto_id' => 20],
            ['id' => 841, 'ciudad' => 'San Martín', 'depto_id' => 50],
            ['id' => 842, 'ciudad' => 'San Martín de Loba', 'depto_id' => 13],
            ['id' => 843, 'ciudad' => 'San Mateo', 'depto_id' => 15],
            ['id' => 844, 'ciudad' => 'San Miguel', 'depto_id' => 68],
            ['id' => 845, 'ciudad' => 'San Miguel', 'depto_id' => 86],
            ['id' => 846, 'ciudad' => 'San Miguel de Sema', 'depto_id' => 15],
            ['id' => 847, 'ciudad' => 'San Onofre', 'depto_id' => 70],
            ['id' => 848, 'ciudad' => 'San Pablo', 'depto_id' => 13],
            ['id' => 849, 'ciudad' => 'San Pablo', 'depto_id' => 52],
            ['id' => 850, 'ciudad' => 'San Pablo de Borbur', 'depto_id' => 15],
            ['id' => 851, 'ciudad' => 'San Pedro', 'depto_id' => 5],
            ['id' => 852, 'ciudad' => 'San Pedro', 'depto_id' => 70],
            ['id' => 853, 'ciudad' => 'San Pedro', 'depto_id' => 76],
            ['id' => 854, 'ciudad' => 'San Pedro de Cartago', 'depto_id' => 52],
            ['id' => 855, 'ciudad' => 'San Pedro de Urabá', 'depto_id' => 5],
            ['id' => 856, 'ciudad' => 'San Pelayo', 'depto_id' => 23],
            ['id' => 857, 'ciudad' => 'San Rafael', 'depto_id' => 5],
            ['id' => 858, 'ciudad' => 'San Roque', 'depto_id' => 5],
            ['id' => 859, 'ciudad' => 'San Sebastián', 'depto_id' => 19],
            ['id' => 860, 'ciudad' => 'San Sebastián de Buenavista', 'depto_id' => 47],
            ['id' => 861, 'ciudad' => 'San Vicente', 'depto_id' => 5],
            ['id' => 862, 'ciudad' => 'San Vicente del Caguán', 'depto_id' => 18],
            ['id' => 863, 'ciudad' => 'San Vicente del Chucurí', 'depto_id' => 68],
            ['id' => 864, 'ciudad' => 'San Zenón', 'depto_id' => 47],
            ['id' => 865, 'ciudad' => 'Sandoná', 'depto_id' => 52],
            ['id' => 866, 'ciudad' => 'Santa Ana', 'depto_id' => 47],
            ['id' => 867, 'ciudad' => 'Santa Bárbara', 'depto_id' => 5],
            ['id' => 868, 'ciudad' => 'Santa Bárbara', 'depto_id' => 68],
            ['id' => 869, 'ciudad' => 'Santa Bárbara (Iscuandé)', 'depto_id' => 52],
            ['id' => 870, 'ciudad' => 'Santa Bárbara de Pinto', 'depto_id' => 47],
            ['id' => 871, 'ciudad' => 'Santa Catalina', 'depto_id' => 13],
            ['id' => 872, 'ciudad' => 'Santa Fé de Antioquia', 'depto_id' => 5],
            ['id' => 873, 'ciudad' => 'Santa Genoveva de Docorodó', 'depto_id' => 27],
            ['id' => 874, 'ciudad' => 'Santa Helena del Opón', 'depto_id' => 68],
            ['id' => 875, 'ciudad' => 'Santa Isabel', 'depto_id' => 73],
            ['id' => 876, 'ciudad' => 'Santa Lucía', 'depto_id' => 8],
            ['id' => 877, 'ciudad' => 'Santa Marta', 'depto_id' => 47],
            ['id' => 878, 'ciudad' => 'Santa María', 'depto_id' => 15],
            ['id' => 879, 'ciudad' => 'Santa María', 'depto_id' => 41],
            ['id' => 880, 'ciudad' => 'Santa Rosa', 'depto_id' => 13],
            ['id' => 881, 'ciudad' => 'Santa Rosa', 'depto_id' => 19],
            ['id' => 882, 'ciudad' => 'Santa Rosa de Cabal', 'depto_id' => 66],
            ['id' => 883, 'ciudad' => 'Santa Rosa de Osos', 'depto_id' => 5],
            ['id' => 884, 'ciudad' => 'Santa Rosa de Viterbo', 'depto_id' => 15],
            ['id' => 885, 'ciudad' => 'Santa Rosa del Sur', 'depto_id' => 13],
            ['id' => 886, 'ciudad' => 'Santa Rosalía', 'depto_id' => 99],
            ['id' => 887, 'ciudad' => 'Santa Sofía', 'depto_id' => 15],
            ['id' => 888, 'ciudad' => 'Santana', 'depto_id' => 15],
            ['id' => 889, 'ciudad' => 'Santander de Quilichao', 'depto_id' => 19],
            ['id' => 890, 'ciudad' => 'Santiago', 'depto_id' => 54],
            ['id' => 891, 'ciudad' => 'Santiago', 'depto_id' => 86],
            ['id' => 892, 'ciudad' => 'Santo Domingo', 'depto_id' => 5],
            ['id' => 893, 'ciudad' => 'Santo Tomás', 'depto_id' => 8],
            ['id' => 894, 'ciudad' => 'Santuario', 'depto_id' => 5],
            ['id' => 895, 'ciudad' => 'Santuario', 'depto_id' => 66],
            ['id' => 896, 'ciudad' => 'Sapuyes', 'depto_id' => 52],
            ['id' => 897, 'ciudad' => 'Saravena', 'depto_id' => 81],
            ['id' => 898, 'ciudad' => 'Sardinata', 'depto_id' => 54],
            ['id' => 899, 'ciudad' => 'Sasaima', 'depto_id' => 25],
            ['id' => 900, 'ciudad' => 'Sativanorte', 'depto_id' => 15],
            ['id' => 901, 'ciudad' => 'Sativasur', 'depto_id' => 15],
            ['id' => 902, 'ciudad' => 'Segovia', 'depto_id' => 5],
            ['id' => 903, 'ciudad' => 'Sesquilé', 'depto_id' => 25],
            ['id' => 904, 'ciudad' => 'Sevilla', 'depto_id' => 76],
            ['id' => 905, 'ciudad' => 'Siachoque', 'depto_id' => 15],
            ['id' => 906, 'ciudad' => 'Sibaté', 'depto_id' => 25],
            ['id' => 907, 'ciudad' => 'Sibundoy', 'depto_id' => 86],
            ['id' => 908, 'ciudad' => 'Silos', 'depto_id' => 54],
            ['id' => 909, 'ciudad' => 'Silvania', 'depto_id' => 25],
            ['id' => 910, 'ciudad' => 'Silvia', 'depto_id' => 19],
            ['id' => 911, 'ciudad' => 'Simacota', 'depto_id' => 68],
            ['id' => 912, 'ciudad' => 'Simijaca', 'depto_id' => 25],
            ['id' => 913, 'ciudad' => 'Simití', 'depto_id' => 13],
            ['id' => 914, 'ciudad' => 'Sincelejo', 'depto_id' => 70],
            ['id' => 915, 'ciudad' => 'Sincé', 'depto_id' => 70],
            ['id' => 916, 'ciudad' => 'Sipí', 'depto_id' => 27],
            ['id' => 917, 'ciudad' => 'Sitionuevo', 'depto_id' => 47],
            ['id' => 918, 'ciudad' => 'Soacha', 'depto_id' => 25],
            ['id' => 919, 'ciudad' => 'Soatá', 'depto_id' => 15],
            ['id' => 920, 'ciudad' => 'Socha', 'depto_id' => 15],
            ['id' => 921, 'ciudad' => 'Socorro', 'depto_id' => 68],
            ['id' => 922, 'ciudad' => 'Socotá', 'depto_id' => 15],
            ['id' => 923, 'ciudad' => 'Sogamoso', 'depto_id' => 15],
            ['id' => 924, 'ciudad' => 'Solano', 'depto_id' => 18],
            ['id' => 925, 'ciudad' => 'Soledad', 'depto_id' => 8],
            ['id' => 926, 'ciudad' => 'Solita', 'depto_id' => 18],
            ['id' => 927, 'ciudad' => 'Somondoco', 'depto_id' => 15],
            ['id' => 928, 'ciudad' => 'Sonsón', 'depto_id' => 5],
            ['id' => 929, 'ciudad' => 'Sopetrán', 'depto_id' => 5],
            ['id' => 930, 'ciudad' => 'Soplaviento', 'depto_id' => 13],
            ['id' => 931, 'ciudad' => 'Sopó', 'depto_id' => 25],
            ['id' => 932, 'ciudad' => 'Sora', 'depto_id' => 15],
            ['id' => 933, 'ciudad' => 'Soracá', 'depto_id' => 15],
            ['id' => 934, 'ciudad' => 'Sotaquirá', 'depto_id' => 15],
            ['id' => 935, 'ciudad' => 'Sotara (Paispamba)', 'depto_id' => 19],
            ['id' => 936, 'ciudad' => 'Sotomayor (Los Andes)', 'depto_id' => 52],
            ['id' => 937, 'ciudad' => 'Suaita', 'depto_id' => 68],
            ['id' => 938, 'ciudad' => 'Suan', 'depto_id' => 8],
            ['id' => 939, 'ciudad' => 'Suaza', 'depto_id' => 41],
            ['id' => 940, 'ciudad' => 'Subachoque', 'depto_id' => 25],
            ['id' => 941, 'ciudad' => 'Sucre', 'depto_id' => 19],
            ['id' => 942, 'ciudad' => 'Sucre', 'depto_id' => 68],
            ['id' => 943, 'ciudad' => 'Sucre', 'depto_id' => 70],
            ['id' => 944, 'ciudad' => 'Suesca', 'depto_id' => 25],
            ['id' => 945, 'ciudad' => 'Supatá', 'depto_id' => 25],
            ['id' => 946, 'ciudad' => 'Supía', 'depto_id' => 17],
            ['id' => 947, 'ciudad' => 'Suratá', 'depto_id' => 68],
            ['id' => 948, 'ciudad' => 'Susa', 'depto_id' => 25],
            ['id' => 949, 'ciudad' => 'Susacón', 'depto_id' => 15],
            ['id' => 950, 'ciudad' => 'Sutamarchán', 'depto_id' => 15],
            ['id' => 951, 'ciudad' => 'Sutatausa', 'depto_id' => 25],
            ['id' => 952, 'ciudad' => 'Sutatenza', 'depto_id' => 15],
            ['id' => 953, 'ciudad' => 'Suárez', 'depto_id' => 19],
            ['id' => 954, 'ciudad' => 'Suárez', 'depto_id' => 73],
            ['id' => 955, 'ciudad' => 'Sácama', 'depto_id' => 85],
            ['id' => 956, 'ciudad' => 'Sáchica', 'depto_id' => 15],
            ['id' => 957, 'ciudad' => 'Tabio', 'depto_id' => 25],
            ['id' => 958, 'ciudad' => 'Tadó', 'depto_id' => 27],
            ['id' => 959, 'ciudad' => 'Talaigua Nuevo', 'depto_id' => 13],
            ['id' => 960, 'ciudad' => 'Tamalameque', 'depto_id' => 20],
            ['id' => 961, 'ciudad' => 'Tame', 'depto_id' => 81],
            ['id' => 962, 'ciudad' => 'Taminango', 'depto_id' => 52],
            ['id' => 963, 'ciudad' => 'Tangua', 'depto_id' => 52],
            ['id' => 964, 'ciudad' => 'Taraira', 'depto_id' => 97],
            ['id' => 965, 'ciudad' => 'Tarazá', 'depto_id' => 5],
            ['id' => 966, 'ciudad' => 'Tarqui', 'depto_id' => 41],
            ['id' => 967, 'ciudad' => 'Tarso', 'depto_id' => 5],
            ['id' => 968, 'ciudad' => 'Tasco', 'depto_id' => 15],
            ['id' => 969, 'ciudad' => 'Tauramena', 'depto_id' => 85],
            ['id' => 970, 'ciudad' => 'Tausa', 'depto_id' => 25],
            ['id' => 971, 'ciudad' => 'Tello', 'depto_id' => 41],
            ['id' => 972, 'ciudad' => 'Tena', 'depto_id' => 25],
            ['id' => 973, 'ciudad' => 'Tenerife', 'depto_id' => 47],
            ['id' => 974, 'ciudad' => 'Tenjo', 'depto_id' => 25],
            ['id' => 975, 'ciudad' => 'Tenza', 'depto_id' => 15],
            ['id' => 976, 'ciudad' => 'Teorama', 'depto_id' => 54],
            ['id' => 977, 'ciudad' => 'Teruel', 'depto_id' => 41],
            ['id' => 978, 'ciudad' => 'Tesalia', 'depto_id' => 41],
            ['id' => 979, 'ciudad' => 'Tibacuy', 'depto_id' => 25],
            ['id' => 980, 'ciudad' => 'Tibaná', 'depto_id' => 15],
            ['id' => 981, 'ciudad' => 'Tibasosa', 'depto_id' => 15],
            ['id' => 982, 'ciudad' => 'Tibirita', 'depto_id' => 25],
            ['id' => 983, 'ciudad' => 'Tibú', 'depto_id' => 54],
            ['id' => 984, 'ciudad' => 'Tierralta', 'depto_id' => 23],
            ['id' => 985, 'ciudad' => 'Timaná', 'depto_id' => 41],
            ['id' => 986, 'ciudad' => 'Timbiquí', 'depto_id' => 19],
            ['id' => 987, 'ciudad' => 'Timbío', 'depto_id' => 19],
            ['id' => 988, 'ciudad' => 'Tinjacá', 'depto_id' => 15],
            ['id' => 989, 'ciudad' => 'Tipacoque', 'depto_id' => 15],
            ['id' => 990, 'ciudad' => 'Tiquisio (Puerto Rico)', 'depto_id' => 13],
            ['id' => 991, 'ciudad' => 'Titiribí', 'depto_id' => 5],
            ['id' => 992, 'ciudad' => 'Toca', 'depto_id' => 15],
            ['id' => 993, 'ciudad' => 'Tocaima', 'depto_id' => 25],
            ['id' => 994, 'ciudad' => 'Tocancipá', 'depto_id' => 25],
            ['id' => 995, 'ciudad' => 'Toguí', 'depto_id' => 15],
            ['id' => 996, 'ciudad' => 'Toledo', 'depto_id' => 5],
            ['id' => 997, 'ciudad' => 'Toledo', 'depto_id' => 54],
            ['id' => 998, 'ciudad' => 'Tolú', 'depto_id' => 70],
            ['id' => 999, 'ciudad' => 'Tolú Viejo', 'depto_id' => 70],
            ['id' => 1000, 'ciudad' => 'Tona', 'depto_id' => 68],
            ['id' => 1001, 'ciudad' => 'Topagá', 'depto_id' => 15],
            ['id' => 1002, 'ciudad' => 'Topaipí', 'depto_id' => 25],
            ['id' => 1003, 'ciudad' => 'Toribío', 'depto_id' => 19],
            ['id' => 1004, 'ciudad' => 'Toro', 'depto_id' => 76],
            ['id' => 1005, 'ciudad' => 'Tota', 'depto_id' => 15],
            ['id' => 1006, 'ciudad' => 'Totoró', 'depto_id' => 19],
            ['id' => 1007, 'ciudad' => 'Trinidad', 'depto_id' => 85],
            ['id' => 1008, 'ciudad' => 'Trujillo', 'depto_id' => 76],
            ['id' => 1009, 'ciudad' => 'Tubará', 'depto_id' => 8],
            ['id' => 1010, 'ciudad' => 'Tuchín', 'depto_id' => 23],
            ['id' => 1011, 'ciudad' => 'Tulúa', 'depto_id' => 76],
            ['id' => 1012, 'ciudad' => 'Tumaco', 'depto_id' => 52],
            ['id' => 1013, 'ciudad' => 'Tunja', 'depto_id' => 15],
            ['id' => 1014, 'ciudad' => 'Tunungua', 'depto_id' => 15],
            ['id' => 1015, 'ciudad' => 'Turbaco', 'depto_id' => 13],
            ['id' => 1016, 'ciudad' => 'Turbaná', 'depto_id' => 13],
            ['id' => 1017, 'ciudad' => 'Turbo', 'depto_id' => 5],
            ['id' => 1018, 'ciudad' => 'Turmequé', 'depto_id' => 15],
            ['id' => 1019, 'ciudad' => 'Tuta', 'depto_id' => 15],
            ['id' => 1020, 'ciudad' => 'Tutasá', 'depto_id' => 15],
            ['id' => 1021, 'ciudad' => 'Támara', 'depto_id' => 85],
            ['id' => 1022, 'ciudad' => 'Támesis', 'depto_id' => 5],
            ['id' => 1023, 'ciudad' => 'Túquerres', 'depto_id' => 52],
            ['id' => 1024, 'ciudad' => 'Ubalá', 'depto_id' => 25],
            ['id' => 1025, 'ciudad' => 'Ubaque', 'depto_id' => 25],
            ['id' => 1026, 'ciudad' => 'Ubaté', 'depto_id' => 25],
            ['id' => 1027, 'ciudad' => 'Ulloa', 'depto_id' => 76],
            ['id' => 1028, 'ciudad' => 'Une', 'depto_id' => 25],
            ['id' => 1029, 'ciudad' => 'Unguía', 'depto_id' => 27],
            ['id' => 1030, 'ciudad' => 'Unión Panamericana (ÁNIMAS)', 'depto_id' => 27],
            ['id' => 1031, 'ciudad' => 'Uramita', 'depto_id' => 5],
            ['id' => 1032, 'ciudad' => 'Uribe', 'depto_id' => 50],
            ['id' => 1033, 'ciudad' => 'Uribia', 'depto_id' => 44],
            ['id' => 1034, 'ciudad' => 'Urrao', 'depto_id' => 5],
            ['id' => 1035, 'ciudad' => 'Urumita', 'depto_id' => 44],
            ['id' => 1036, 'ciudad' => 'Usiacuri', 'depto_id' => 8],
            ['id' => 1037, 'ciudad' => 'Valdivia', 'depto_id' => 5],
            ['id' => 1038, 'ciudad' => 'Valencia', 'depto_id' => 23],
            ['id' => 1039, 'ciudad' => 'Valle de San José', 'depto_id' => 68],
            ['id' => 1040, 'ciudad' => 'Valle de San Juan', 'depto_id' => 73],
            ['id' => 1041, 'ciudad' => 'Valle del Guamuez', 'depto_id' => 86],
            ['id' => 1042, 'ciudad' => 'Valledupar', 'depto_id' => 20],
            ['id' => 1043, 'ciudad' => 'Valparaiso', 'depto_id' => 5],
            ['id' => 1044, 'ciudad' => 'Valparaiso', 'depto_id' => 18],
            ['id' => 1045, 'ciudad' => 'Vegachí', 'depto_id' => 5],
            ['id' => 1046, 'ciudad' => 'Venadillo', 'depto_id' => 73],
            ['id' => 1047, 'ciudad' => 'Venecia', 'depto_id' => 5],
            ['id' => 1048, 'ciudad' => 'Venecia (Ospina Pérez)', 'depto_id' => 25],
            ['id' => 1049, 'ciudad' => 'Ventaquemada', 'depto_id' => 15],
            ['id' => 1050, 'ciudad' => 'Vergara', 'depto_id' => 25],
            ['id' => 1051, 'ciudad' => 'Versalles', 'depto_id' => 76],
            ['id' => 1052, 'ciudad' => 'Vetas', 'depto_id' => 68],
            ['id' => 1053, 'ciudad' => 'Viani', 'depto_id' => 25],
            ['id' => 1054, 'ciudad' => 'Vigía del Fuerte', 'depto_id' => 5],
            ['id' => 1055, 'ciudad' => 'Vijes', 'depto_id' => 76],
            ['id' => 1056, 'ciudad' => 'Villa Caro', 'depto_id' => 54],
            ['id' => 1057, 'ciudad' => 'Villa Rica', 'depto_id' => 19],
            ['id' => 1058, 'ciudad' => 'Villa de Leiva', 'depto_id' => 15],
            ['id' => 1059, 'ciudad' => 'Villa del Rosario', 'depto_id' => 54],
            ['id' => 1060, 'ciudad' => 'Villagarzón', 'depto_id' => 86],
            ['id' => 1061, 'ciudad' => 'Villagómez', 'depto_id' => 25],
            ['id' => 1062, 'ciudad' => 'Villahermosa', 'depto_id' => 73],
            ['id' => 1063, 'ciudad' => 'Villamaría', 'depto_id' => 17],
            ['id' => 1064, 'ciudad' => 'Villanueva', 'depto_id' => 13],
            ['id' => 1065, 'ciudad' => 'Villanueva', 'depto_id' => 44],
            ['id' => 1066, 'ciudad' => 'Villanueva', 'depto_id' => 68],
            ['id' => 1067, 'ciudad' => 'Villanueva', 'depto_id' => 85],
            ['id' => 1068, 'ciudad' => 'Villapinzón', 'depto_id' => 25],
            ['id' => 1069, 'ciudad' => 'Villarrica', 'depto_id' => 73],
            ['id' => 1070, 'ciudad' => 'Villavicencio', 'depto_id' => 50],
            ['id' => 1071, 'ciudad' => 'Villavieja', 'depto_id' => 41],
            ['id' => 1072, 'ciudad' => 'Villeta', 'depto_id' => 25],
            ['id' => 1073, 'ciudad' => 'Viotá', 'depto_id' => 25],
            ['id' => 1074, 'ciudad' => 'Viracachá', 'depto_id' => 15],
            ['id' => 1075, 'ciudad' => 'Vista Hermosa', 'depto_id' => 50],
            ['id' => 1076, 'ciudad' => 'Viterbo', 'depto_id' => 17],
            ['id' => 1077, 'ciudad' => 'Vélez', 'depto_id' => 68],
            ['id' => 1078, 'ciudad' => 'Yacopí', 'depto_id' => 25],
            ['id' => 1079, 'ciudad' => 'Yacuanquer', 'depto_id' => 52],
            ['id' => 1080, 'ciudad' => 'Yaguará', 'depto_id' => 41],
            ['id' => 1081, 'ciudad' => 'Yalí', 'depto_id' => 5],
            ['id' => 1082, 'ciudad' => 'Yarumal', 'depto_id' => 5],
            ['id' => 1083, 'ciudad' => 'Yolombó', 'depto_id' => 5],
            ['id' => 1084, 'ciudad' => 'Yondó (Casabe)', 'depto_id' => 5],
            ['id' => 1085, 'ciudad' => 'Yopal', 'depto_id' => 85],
            ['id' => 1086, 'ciudad' => 'Yotoco', 'depto_id' => 76],
            ['id' => 1087, 'ciudad' => 'Yumbo', 'depto_id' => 76],
            ['id' => 1088, 'ciudad' => 'Zambrano', 'depto_id' => 13],
            ['id' => 1089, 'ciudad' => 'Zapatoca', 'depto_id' => 68],
            ['id' => 1090, 'ciudad' => 'Zapayán (PUNTA DE PIEDRAS)', 'depto_id' => 47],
            ['id' => 1091, 'ciudad' => 'Zaragoza', 'depto_id' => 5],
            ['id' => 1092, 'ciudad' => 'Zarzal', 'depto_id' => 76],
            ['id' => 1093, 'ciudad' => 'Zetaquirá', 'depto_id' => 15],
            ['id' => 1094, 'ciudad' => 'Zipacón', 'depto_id' => 25],
            ['id' => 1095, 'ciudad' => 'Zipaquirá', 'depto_id' => 25],
            ['id' => 1096, 'ciudad' => 'Zona Bananera (PRADO - SEVILLA)', 'depto_id' => 47],
            ['id' => 1097, 'ciudad' => 'Ábrego', 'depto_id' => 54],
            ['id' => 1098, 'ciudad' => 'Íquira', 'depto_id' => 41],
            ['id' => 1099, 'ciudad' => 'Úmbita', 'depto_id' => 15],
            ['id' => 1100, 'ciudad' => 'Útica', 'depto_id' => 25],
        ]);
    }
}