<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UnidadesMedidaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        \DB::table('unidades_medidas')->insert([
            ['id' =>1, 'codigo' =>'04', 'descripcion' => 'spray pequeño'],
            ['id' =>2, 'codigo' =>'05', 'descripcion' => 'levantar'],
            ['id' =>3, 'codigo' =>'08', 'descripcion' => 'Lote calor'],
            ['id' =>4, 'codigo' =>'10', 'descripcion' => 'grupo'],
            ['id' =>5, 'codigo' =>'11', 'descripcion' => 'equipar'],
            ['id' =>6, 'codigo' =>'13', 'descripcion' => 'ración'],
            ['id' =>7, 'codigo' =>'14', 'descripcion' => 'Disparo'],
            ['id' =>8, 'codigo' =>'15', 'descripcion' => 'palo'],
            ['id' =>9, 'codigo' =>'16', 'descripcion' => 'tambor de ciento quince kg'],
            ['id' =>10, 'codigo' =>'17', 'descripcion' => 'tambor de cien libras'],
            ['id' =>11, 'codigo' =>'18', 'descripcion' => 'tambor de cincuenta y cinco galones (US)'],
            ['id' =>12, 'codigo' =>'19', 'descripcion' => 'camión cisterna'],
            ['id' =>13, 'codigo' =>'20', 'descripcion' => 'contenedor de veinte pies'],
            ['id' =>14, 'codigo' =>'21', 'descripcion' => 'contenedor de cuarenta pies'],
            ['id' =>15, 'codigo' =>'22', 'descripcion' => 'decilitro por gramo'],
            ['id' =>16, 'codigo' =>'23', 'descripcion' => 'gramo por centímetro cúbico'],
            ['id' =>17, 'codigo' =>'24', 'descripcion' => 'libra teórica'],
            ['id' =>18, 'codigo' =>'25', 'descripcion' => 'gramo por centímetro cuadrado'],
            ['id' =>19, 'codigo' =>'26', 'descripcion' => 'tonelada real'],
            ['id' =>20, 'codigo' =>'27', 'descripcion' => 'tonelada teórica'],
            ['id' =>21, 'codigo' =>'28', 'descripcion' => 'kilogramo por metro cuadrado'],
            ['id' =>22, 'codigo' =>'29', 'descripcion' => 'libra por mil pies cuadrados'],
            ['id' =>23, 'codigo' =>'30', 'descripcion' => 'Día de potencia del caballo por tonelada métrica seca al aire.'],
            ['id' =>24, 'codigo' =>'31', 'descripcion' => 'coger peso'],
            ['id' =>25, 'codigo' =>'32', 'descripcion' => 'kilogramo por aire seco tonelada métrica'],
            ['id' =>26, 'codigo' =>'33', 'descripcion' => 'kilopascales metros cuadrados por gramo'],
            ['id' =>27, 'codigo' =>'34', 'descripcion' => 'kilopascales por milímetro'],
            ['id' =>28, 'codigo' =>'35', 'descripcion' => 'mililitros por centímetro cuadrado segundo'],
            ['id' =>29, 'codigo' =>'36', 'descripcion' => 'pies cúbicos por minuto por pie cuadrado'],
            ['id' =>30, 'codigo' =>'37', 'descripcion' => 'onza por pie cuadrado'],
            ['id' =>31, 'codigo' =>'38', 'descripcion' => 'onzas por pie cuadrado por 0,01 pulgadas'],
            ['id' =>32, 'codigo' =>'40', 'descripcion' => 'mililitro por segundo'],
            ['id' =>33, 'codigo' =>'41', 'descripcion' => 'mililitro por minuto'],
            ['id' =>34, 'codigo' =>'43', 'descripcion' => 'bolsa súper a granel'],
            ['id' =>35, 'codigo' =>'44', 'descripcion' => 'bolsa a granel de quinientos kg'],
            ['id' =>36, 'codigo' =>'45', 'descripcion' => 'bolsa a granel de trescientos kg'],
            ['id' =>37, 'codigo' =>'46', 'descripcion' => 'bolsa a granel de cincuenta libras'],
            ['id' =>38, 'codigo' =>'47', 'descripcion' => 'bolsa de cincuenta libras'],
            ['id' =>39, 'codigo' =>'48', 'descripcion' => 'carga de automóviles a granel'],
            ['id' =>40, 'codigo' =>'53', 'descripcion' => 'kilogramos teóricos'],
            ['id' =>41, 'codigo' =>'54', 'descripcion' => 'tonelada teórica'],
            ['id' =>42, 'codigo' =>'56', 'descripcion' => 'sitas'],
            ['id' =>43, 'codigo' =>'57', 'descripcion' => 'malla'],
            ['id' =>44, 'codigo' =>'58', 'descripcion' => 'kilogramo neto'],
            ['id' =>45, 'codigo' =>'59', 'descripcion' => 'parte por millón'],
            ['id' =>46, 'codigo' =>'60', 'descripcion' => 'porcentaje de peso'],
            ['id' =>47, 'codigo' =>'61', 'descripcion' => 'parte por billón (US)'],
            ['id' =>48, 'codigo' =>'62', 'descripcion' => 'porcentaje por 1000 horas'],
            ['id' =>49, 'codigo' =>'63', 'descripcion' => 'tasa de fracaso en el tiempo'],
            ['id' =>50, 'codigo' =>'64', 'descripcion' => 'libra por pulgada cuadrada, calibre'],
            ['id' =>51, 'codigo' =>'66', 'descripcion' => 'Oersted'],
            ['id' =>52, 'codigo' =>'69', 'descripcion' => 'prueba de escala específica'],
            ['id' =>53, 'codigo' =>'71', 'descripcion' => 'voltio amperio por libra'],
            ['id' =>54, 'codigo' =>'72', 'descripcion' => 'vatio por libra'],
            ['id' =>55, 'codigo' =>'73', 'descripcion' => 'amperio tum por centímetro'],
            ['id' =>56, 'codigo' =>'74', 'descripcion' => 'milipascal'],
            ['id' =>57, 'codigo' =>'76', 'descripcion' => 'gauss'],
            ['id' =>58, 'codigo' =>'77', 'descripcion' => 'mili pulgadas'],
            ['id' =>59, 'codigo' =>'78', 'descripcion' => 'kilogauss'],
            ['id' =>60, 'codigo' =>'80', 'descripcion' => 'libras por pulgada cuadrada absoluta'],
            ['id' =>61, 'codigo' =>'81', 'descripcion' => 'Enrique'],
            ['id' =>62, 'codigo' =>'84', 'descripcion' => 'kilopound por pulgada cuadrada'],
            ['id' =>63, 'codigo' =>'85', 'descripcion' => 'fuerza libra pie'],
            ['id' =>64, 'codigo' =>'87', 'descripcion' => 'libra por pie cúbico'],
            ['id' =>65, 'codigo' =>'89', 'descripcion' => 'equilibrio'],
            ['id' =>66, 'codigo' =>'90', 'descripcion' => 'Saybold segundo universal'],
            ['id' =>67, 'codigo' =>'91', 'descripcion' => 'alimenta'],
            ['id' =>68, 'codigo' =>'92', 'descripcion' => 'calorías por centímetro cúbico'],
            ['id' =>69, 'codigo' =>'93', 'descripcion' => 'calorías por gramo'],
            ['id' =>70, 'codigo' =>'94', 'descripcion' => 'unidad'],
            ['id' =>71, 'codigo' =>'95', 'descripcion' => 'veinte mil galones (US) de carros'],
            ['id' =>72, 'codigo' =>'96', 'descripcion' => 'diez mil galones (US) de carros'],
            ['id' =>73, 'codigo' =>'97', 'descripcion' => 'tambor de diez kg'],
            ['id' =>74, 'codigo' =>'98', 'descripcion' => 'tambor de quince kg'],
            ['id' =>75, 'codigo' =>'1A', 'descripcion' => 'milla de coche'],
            ['id' =>76, 'codigo' =>'1B', 'descripcion' => 'recuento de coches'],
            ['id' =>77, 'codigo' =>'1C', 'descripcion' => 'recuento de locomotoras'],
            ['id' =>78, 'codigo' =>'1D', 'descripcion' => 'recuento de cabos'],
            ['id' =>79, 'codigo' =>'1E', 'descripcion' => 'carro vacio'],
            ['id' =>80, 'codigo' =>'1F', 'descripcion' => 'millas de tren'],
            ['id' =>81, 'codigo' =>'1G', 'descripcion' => 'uso de combustible galón (US)'],
            ['id' =>82, 'codigo' =>'1H', 'descripcion' => 'milla del caboose'],
            ['id' =>83, 'codigo' =>'1I', 'descripcion' => 'tipo de interés fijo'],
            ['id' =>84, 'codigo' =>'1J', 'descripcion' => 'tonelada milla'],
            ['id' =>85, 'codigo' =>'1K', 'descripcion' => 'milla locomotora'],
            ['id' =>86, 'codigo' =>'1L', 'descripcion' => 'recuento total de coches'],
            ['id' =>87, 'codigo' =>'1M', 'descripcion' => 'milla de coche total'],
            ['id' =>88, 'codigo' =>'1X', 'descripcion' => 'cuarto de milla'],
            ['id' =>89, 'codigo' =>'2A', 'descripcion' => 'radianes por segundo'],
            ['id' =>90, 'codigo' =>'2B', 'descripcion' => 'radianes por segundo al cuadrado'],
            ['id' =>91, 'codigo' =>'2C', 'descripcion' => 'Röntgen'],
            ['id' =>92, 'codigo' =>'2I', 'descripcion' => 'Unidad térmica británica por hora.'],
            ['id' =>93, 'codigo' =>'2J', 'descripcion' => 'centímetro cúbico por segundo'],
            ['id' =>94, 'codigo' =>'2K', 'descripcion' => 'pie cúbico por hora'],
            ['id' =>95, 'codigo' =>'2L', 'descripcion' => 'pie cúbico por minuto'],
            ['id' =>96, 'codigo' =>'2M', 'descripcion' => 'centímetro por segundo'],
            ['id' =>97, 'codigo' =>'2N', 'descripcion' => 'decibel'],
            ['id' =>98, 'codigo' =>'2P', 'descripcion' => 'kilobyte'],
            ['id' =>99, 'codigo' =>'2Q', 'descripcion' => 'kilobecquerel'],
            ['id' =>100, 'codigo' =>'2R', 'descripcion' => 'kilocurie'],
            ['id' =>101, 'codigo' =>'2U', 'descripcion' => 'megagramo'],
            ['id' =>102, 'codigo' =>'2V', 'descripcion' => 'megagramo por hora'],
            ['id' =>103, 'codigo' =>'2W', 'descripcion' => 'compartimiento'],
            ['id' =>104, 'codigo' =>'2X', 'descripcion' => 'metro por minuto'],
            ['id' =>105, 'codigo' =>'2Y', 'descripcion' => 'milliröntgen'],
            ['id' =>106, 'codigo' =>'2Z', 'descripcion' => 'milivoltios'],
            ['id' =>107, 'codigo' =>'3B', 'descripcion' => 'megajulio'],
            ['id' =>108, 'codigo' =>'3C', 'descripcion' => 'manmonth'],
            ['id' =>109, 'codigo' =>'3E', 'descripcion' => 'libra por libra de producto'],
            ['id' =>110, 'codigo' =>'3G', 'descripcion' => 'libra por pieza de producto'],
            ['id' =>111, 'codigo' =>'3H', 'descripcion' => 'kilogramo por kilogramo de producto'],
            ['id' =>112, 'codigo' =>'3I', 'descripcion' => 'kilogramo por pieza de producto'],
            ['id' =>113, 'codigo' =>'4A', 'descripcion' => 'bobina'],
            ['id' =>114, 'codigo' =>'4B', 'descripcion' => 'gorra'],
            ['id' =>115, 'codigo' =>'4C', 'descripcion' => 'centistokes'],
            ['id' =>116, 'codigo' =>'4E', 'descripcion' => 'paquete de veinte'],
            ['id' =>117, 'codigo' =>'4G', 'descripcion' => 'microlitro'],
            ['id' =>118, 'codigo' =>'4H', 'descripcion' => 'micrometro'],
            ['id' =>119, 'codigo' =>'4K', 'descripcion' => 'miliamperio'],
            ['id' =>120, 'codigo' =>'4L', 'descripcion' => 'megabyte'],
            ['id' =>121, 'codigo' =>'4M', 'descripcion' => 'miligramo por hora'],
            ['id' =>122, 'codigo' =>'4N', 'descripcion' => 'megabecquerel'],
            ['id' =>123, 'codigo' =>'4O', 'descripcion' => 'microfarad'],
            ['id' =>124, 'codigo' =>'4P', 'descripcion' => 'newton por metro'],
            ['id' =>125, 'codigo' =>'4Q', 'descripcion' => 'onza pulgada'],
            ['id' =>126, 'codigo' =>'4R', 'descripcion' => 'pie onza'],
            ['id' =>127, 'codigo' =>'4T', 'descripcion' => 'picofarad'],
            ['id' =>128, 'codigo' =>'4U', 'descripcion' => 'libra por hora'],
            ['id' =>129, 'codigo' =>'4W', 'descripcion' => 'tonelada (US) por hora'],
            ['id' =>130, 'codigo' =>'4X', 'descripcion' => 'kilolitro por hora'],
            ['id' =>131, 'codigo' =>'5A', 'descripcion' => 'barril por minuto'],
            ['id' =>132, 'codigo' =>'5B', 'descripcion' => 'lote'],
            ['id' =>133, 'codigo' =>'5C', 'descripcion' => 'galón (US) por mil'],
            ['id' =>134, 'codigo' =>'5E', 'descripcion' => 'MMSCF / día'],
            ['id' =>135, 'codigo' =>'5F', 'descripcion' => 'libras por mil'],
            ['id' =>136, 'codigo' =>'5G', 'descripcion' => 'bomba'],
            ['id' =>137, 'codigo' =>'5H', 'descripcion' => 'escenario'],
            ['id' =>138, 'codigo' =>'5I', 'descripcion' => 'pie cúbico estándar'],
            ['id' =>139, 'codigo' =>'5J', 'descripcion' => 'potencia hidráulica de caballos'],
            ['id' =>140, 'codigo' =>'5K', 'descripcion' => 'contar por minuto'],
            ['id' =>141, 'codigo' =>'5P', 'descripcion' => 'nivel sismico'],
            ['id' =>142, 'codigo' =>'5Q', 'descripcion' => '247nfor sismica'],
            ['id' =>143, 'codigo' =>'A1', 'descripcion' => '15 calorías C'],
            ['id' =>144, 'codigo' =>'A10', 'descripcion' => 'amperio metro cuadrado por joule segundo'],
            ['id' =>145, 'codigo' =>'A11', 'descripcion' => 'Ã ¥ ngström'],
            ['id' =>146, 'codigo' =>'A12', 'descripcion' => 'unidad astronómica'],
            ['id' =>147, 'codigo' =>'A13', 'descripcion' => 'attojoule'],
            ['id' =>148, 'codigo' =>'A14', 'descripcion' => 'granero'],
            ['id' =>149, 'codigo' =>'A15', 'descripcion' => 'granero por electrón voltio'],
            ['id' =>150, 'codigo' =>'A16', 'descripcion' => 'granero por voltio de electrones esteradiano,'],
            ['id' =>151, 'codigo' =>'A17', 'descripcion' => 'granero por sterdian'],
            ['id' =>152, 'codigo' =>'A18', 'descripcion' => 'becquerel por kilogramo'],
            ['id' =>153, 'codigo' =>'A19', 'descripcion' => 'becquerel por metro cúbico'],
            ['id' =>154, 'codigo' =>'A2', 'descripcion' => 'amperio por centímetro'],
            ['id' =>155, 'codigo' =>'A20', 'descripcion' => 'Unidad térmica británica por segundo pie cuadrado grado Rankin'],
            ['id' =>156, 'codigo' =>'A21', 'descripcion' => 'Unidad térmica británica por libra grado Rankin'],
            ['id' =>157, 'codigo' =>'A22', 'descripcion' => 'Unidad térmica británica por segundo pie grado Rankin'],
            ['id' =>158, 'codigo' =>'A23', 'descripcion' => 'Unidad térmica británica por hora pie cuadrado grado Rankin'],
            ['id' =>159, 'codigo' =>'A24', 'descripcion' => 'candela por metro cuadrado'],
            ['id' =>160, 'codigo' =>'A25', 'descripcion' => 'cheval vapeur'],
            ['id' =>161, 'codigo' =>'A26', 'descripcion' => 'medidor de culombio'],
            ['id' =>162, 'codigo' =>'A27', 'descripcion' => 'medidor de culombio al cuadrado por voltio'],
            ['id' =>163, 'codigo' =>'A28', 'descripcion' => 'Coulomb por centímetro cúbico'],
            ['id' =>164, 'codigo' =>'A29', 'descripcion' => 'Coulomb por metro cúbico'],
            ['id' =>165, 'codigo' =>'A3', 'descripcion' => 'amperio por milímetro'],
            ['id' =>166, 'codigo' =>'A30', 'descripcion' => 'Coulomb por milímetro cúbico'],
            ['id' =>167, 'codigo' =>'A31', 'descripcion' => 'Coulomb por kilogramo segundo'],
            ['id' =>168, 'codigo' =>'A32', 'descripcion' => 'Coulomb por mol'],
            ['id' =>169, 'codigo' =>'A33', 'descripcion' => 'Coulomb por centímetro cuadrado'],
            ['id' =>170, 'codigo' =>'A34', 'descripcion' => 'Coulomb por metro cuadrado'],
            ['id' =>171, 'codigo' =>'A35', 'descripcion' => 'Coulomb por milímetro cuadrado'],
            ['id' =>172, 'codigo' =>'A36', 'descripcion' => 'centímetro cúbico por mol'],
            ['id' =>173, 'codigo' =>'A37', 'descripcion' => '247nformaci cúbico por mol'],
            ['id' =>174, 'codigo' =>'A38', 'descripcion' => 'metro cúbico por coulomb'],
            ['id' =>175, 'codigo' =>'A39', 'descripcion' => 'metro cúbico por kilogramo'],
            ['id' =>176, 'codigo' =>'A4', 'descripcion' => 'amperio por centímetro cuadrado'],
            ['id' =>177, 'codigo' =>'A40', 'descripcion' => 'metro cúbico por mol'],
            ['id' =>178, 'codigo' =>'A41', 'descripcion' => 'amperio por metro cuadrado'],
            ['id' =>179, 'codigo' =>'A42', 'descripcion' => 'curie por kilogramo'],
            ['id' =>180, 'codigo' =>'A43', 'descripcion' => 'tonelaje de peso muerto'],
            ['id' =>181, 'codigo' =>'A44', 'descripcion' => 'decalitro'],
            ['id' =>182, 'codigo' =>'A45', 'descripcion' => 'decámetro'],
            ['id' =>183, 'codigo' =>'A47', 'descripcion' => 'decitex'],
            ['id' =>184, 'codigo' =>'A48', 'descripcion' => 'grado Rankin'],
            ['id' =>185, 'codigo' =>'A49', 'descripcion' => 'negador'],
            ['id' =>186, 'codigo' =>'A5', 'descripcion' => 'amperio metro cuadrado'],
            ['id' =>187, 'codigo' =>'A50', 'descripcion' => 'dyn segundo por centímetro cúbico'],
            ['id' =>188, 'codigo' =>'A51', 'descripcion' => 'dina segundo por centímetro'],
            ['id' =>189, 'codigo' =>'A52', 'descripcion' => 'dina segundo por centímetro al quinto'],
            ['id' =>190, 'codigo' =>'A53', 'descripcion' => 'electronvolt'],
            ['id' =>191, 'codigo' =>'A54', 'descripcion' => 'electronvoltio por metro'],
            ['id' =>192, 'codigo' =>'A55', 'descripcion' => 'metro electronvolt cuadrado'],
            ['id' =>193, 'codigo' =>'A56', 'descripcion' => 'electronvoltio de metro cuadrado por kilogramo'],
            ['id' =>194, 'codigo' =>'A57', 'descripcion' => 'ergio'],
            ['id' =>195, 'codigo' =>'A58', 'descripcion' => 'erg por centímetro'],
            ['id' =>196, 'codigo' =>'A6', 'descripcion' => 'amperio por metro cuadrado kelvin al cuadrado'],
            ['id' =>197, 'codigo' =>'A60', 'descripcion' => 'erg por centímetro cúbico'],
            ['id' =>198, 'codigo' =>'A61', 'descripcion' => 'erg por gramo'],
            ['id' =>199, 'codigo' =>'A62', 'descripcion' => 'erg por gramo de segundo'],
            ['id' =>200, 'codigo' =>'A63', 'descripcion' => 'erg por segundo'],
            ['id' =>201, 'codigo' =>'A64', 'descripcion' => 'erg por segundo centímetro cuadrado'],
            ['id' =>202, 'codigo' =>'A65', 'descripcion' => 'erg por centímetro cuadrado segundo'],
            ['id' =>203, 'codigo' =>'A66', 'descripcion' => 'erg centímetro cuadrado'],
            ['id' =>204, 'codigo' =>'A67', 'descripcion' => 'ergímetro cuadrado por gramo'],
            ['id' =>205, 'codigo' =>'A68', 'descripcion' => 'exajulio'],
            ['id' =>206, 'codigo' =>'A69', 'descripcion' => 'faradio por metro'],
            ['id' =>207, 'codigo' =>'A7', 'descripcion' => 'amperio por milímetro cuadrado'],
            ['id' =>208, 'codigo' =>'A70', 'descripcion' => 'femtojoule'],
            ['id' =>209, 'codigo' =>'A71', 'descripcion' => 'femtometro'],
            ['id' =>210, 'codigo' =>'A73', 'descripcion' => 'pie por segundo al cuadrado'],
            ['id' =>211, 'codigo' =>'A74', 'descripcion' => 'pie-fuerza de la libra por segundo'],
            ['id' =>212, 'codigo' =>'A75', 'descripcion' => 'tonelada de carga'],
            ['id' =>213, 'codigo' =>'A76', 'descripcion' => 'galón'],
            ['id' =>214, 'codigo' =>'A77', 'descripcion' => 'Unidad de desplazamiento CGS gaussiana'],
            ['id' =>215, 'codigo' =>'A78', 'descripcion' => 'Unidad gaussiana CGS de corriente eléctrica.'],
            ['id' =>216, 'codigo' =>'A79', 'descripcion' => 'Unidad Gaussian CGS de carga eléctrica.'],
            ['id' =>217, 'codigo' =>'A8', 'descripcion' => 'amperio segundo'],
            ['id' =>218, 'codigo' =>'A80', 'descripcion' => 'Unidad Gaussian CGS de intensidad de campo eléctrico.'],
            ['id' =>219, 'codigo' =>'A81', 'descripcion' => 'Unidad Gaussian CGS de polarización eléctrica.'],
            ['id' =>220, 'codigo' =>'A82', 'descripcion' => 'Unidad Gaussian CGS de potencial eléctrico.'],
            ['id' =>221, 'codigo' =>'A83', 'descripcion' => 'Unidad Gaussiana CGS de magnetización.'],
            ['id' =>222, 'codigo' =>'A84', 'descripcion' => 'gigacoulomb por metro cúbico'],
            ['id' =>223, 'codigo' =>'A85', 'descripcion' => 'Gigaelectronvolt'],
            ['id' =>224, 'codigo' =>'A86', 'descripcion' => 'gigahercios'],
            ['id' =>225, 'codigo' =>'A87', 'descripcion' => 'gigaohm'],
            ['id' =>226, 'codigo' =>'A88', 'descripcion' => 'medidor de gigaohm'],
            ['id' =>227, 'codigo' =>'A89', 'descripcion' => 'gigapascal'],
            ['id' =>228, 'codigo' =>'A9', 'descripcion' => 'tarifa'],
            ['id' =>229, 'codigo' =>'A90', 'descripcion' => 'gigavatios'],
            ['id' =>230, 'codigo' =>'A91', 'descripcion' => 'gon'],
            ['id' =>231, 'codigo' =>'A93', 'descripcion' => 'gramo por metro cúbico'],
            ['id' =>232, 'codigo' =>'A94', 'descripcion' => 'gramo por mol'],
            ['id' =>233, 'codigo' =>'A95', 'descripcion' => 'gris'],
            ['id' =>234, 'codigo' =>'A96', 'descripcion' => 'gris por segundo'],
            ['id' =>235, 'codigo' =>'A97', 'descripcion' => 'hectopascal'],
            ['id' =>236, 'codigo' =>'A98', 'descripcion' => 'Henry por metro'],
            ['id' =>237, 'codigo' =>'AA', 'descripcion' => 'bola'],
            ['id' =>238, 'codigo' =>'AB', 'descripcion' => 'paquete a granel'],
            ['id' =>239, 'codigo' =>'ACR', 'descripcion' => 'acre'],
            ['id' =>240, 'codigo' =>'AD', 'descripcion' => 'byte'],
            ['id' =>241, 'codigo' =>'AE', 'descripcion' => 'amperio por metro'],
            ['id' =>242, 'codigo' =>'AH', 'descripcion' => 'minuto adicional'],
            ['id' =>243, 'codigo' =>'AI', 'descripcion' => 'minuto promedio por llamada'],
            ['id' =>244, 'codigo' =>'AJ', 'descripcion' => 'policía'],
            ['id' =>245, 'codigo' =>'AK', 'descripcion' => 'braza'],
            ['id' =>246, 'codigo' =>'AL', 'descripcion' => '250nfor de acceso'],
            ['id' =>247, 'codigo' =>'AM', 'descripcion' => 'ampolla'],
            ['id' =>248, 'codigo' =>'AMH', 'descripcion' => 'hora amperio'],
            ['id' =>249, 'codigo' =>'AMP', 'descripcion' => 'amperio'],
            ['id' =>250, 'codigo' =>'ANA', 'descripcion' => 'año'],
            ['id' =>251, 'codigo' =>'AP', 'descripcion' => 'solo libra de aluminio'],
            ['id' =>252, 'codigo' =>'APZ', 'descripcion' => 'onza troy o onza de boticarios'],
            ['id' =>253, 'codigo' =>'AQ', 'descripcion' => 'Unidad de factor antihemofílico (AHF)'],
            ['id' =>254, 'codigo' =>'AR', 'descripcion' => 'supositorio'],
            ['id' =>255, 'codigo' =>'SON', 'descripcion' => 'son'],
            ['id' =>256, 'codigo' =>'COMO', 'descripcion' => 'surtido'],
            ['id' =>257, 'codigo' =>'ASM', 'descripcion' => 'fuerza alcohólica en masa'],
            ['id' =>258, 'codigo' =>'ASU', 'descripcion' => 'fuerza alcohólica por volumen'],
            ['id' =>259, 'codigo' =>'ATM', 'descripcion' => 'ambiente estándar'],
            ['id' =>260, 'codigo' =>'ATT', 'descripcion' => 'ambiente técnico'],
            ['id' =>261, 'codigo' =>'AV', 'descripcion' => 'cápsula'],
            ['id' =>262, 'codigo' =>'AW', 'descripcion' => 'vial lleno de polvo'],
            ['id' =>263, 'codigo' =>'SI', 'descripcion' => 'montaje'],
            ['id' =>264, 'codigo' =>'AZ', 'descripcion' => 'Unidad térmica británica por libra'],
            ['id' =>265, 'codigo' =>'B0', 'descripcion' => 'Btu por pie cúbico'],
            ['id' =>266, 'codigo' =>'B1', 'descripcion' => 'barril (US) por día'],
            ['id' =>267, 'codigo' =>'B11', 'descripcion' => 'julios por kilogramo kelvin'],
            ['id' =>268, 'codigo' =>'B12', 'descripcion' => 'julios por metro'],
            ['id' =>269, 'codigo' =>'B13', 'descripcion' => 'julios por metro cuadrado'],
            ['id' =>270, 'codigo' =>'B14', 'descripcion' => 'julios por metro a la cuarta potencia'],
            ['id' =>271, 'codigo' =>'B15', 'descripcion' => 'julios por mol'],
            ['id' =>272, 'codigo' =>'B16', 'descripcion' => 'julios por mol kelvin'],
            ['id' =>273, 'codigo' =>'B18', 'descripcion' => 'joule segundo'],
            ['id' =>274, 'codigo' =>'B2', 'descripcion' => 'litera'],
            ['id' =>275, 'codigo' =>'B20', 'descripcion' => 'joule metro cuadrado por kilogramo'],
            ['id' =>276, 'codigo' =>'B21', 'descripcion' => 'kelvin por vatio'],
            ['id' =>277, 'codigo' =>'B22', 'descripcion' => 'Kiloampere'],
            ['id' =>278, 'codigo' =>'B23', 'descripcion' => 'kiloampere por metro cuadrado'],
            ['id' =>279, 'codigo' =>'B24', 'descripcion' => 'kiloampere por metro'],
            ['id' =>280, 'codigo' =>'B25', 'descripcion' => 'kilobecquerel por kilogramo'],
            ['id' =>281, 'codigo' =>'B26', 'descripcion' => 'kilocoulomb'],
            ['id' =>282, 'codigo' =>'B27', 'descripcion' => 'kilocoulomb por metro cúbico'],
            ['id' =>283, 'codigo' =>'B28', 'descripcion' => 'kilocoulomb por metro cuadrado'],
            ['id' =>284, 'codigo' =>'B29', 'descripcion' => 'kiloelectronvolt'],
            ['id' =>285, 'codigo' =>'B3', 'descripcion' => 'libra de bateo'],
            ['id' =>286, 'codigo' =>'B31', 'descripcion' => 'kilogramo metro por segundo'],
            ['id' =>287, 'codigo' =>'B32', 'descripcion' => 'kilogramo metro cuadrado'],
            ['id' =>288, 'codigo' =>'B33', 'descripcion' => 'kilogramo metro cuadrado por segundo'],
            ['id' =>289, 'codigo' =>'B34', 'descripcion' => 'kilogramo por decímetro cúbico'],
            ['id' =>290, 'codigo' =>'B35', 'descripcion' => 'kilogramo por litro'],
            ['id' =>291, 'codigo' =>'B36', 'descripcion' => 'caloría termoquímica por gramo'],
            ['id' =>292, 'codigo' =>'B37', 'descripcion' => 'kilogramo de fuerza'],
            ['id' =>293, 'codigo' =>'B38', 'descripcion' => 'metro de fuerza de kilogramo'],
            ['id' =>294, 'codigo' =>'B39', 'descripcion' => 'metro de fuerza de kilogramo por segundo'],
            ['id' =>295, 'codigo' =>'B4', 'descripcion' => 'barril, imperial'],
            ['id' =>296, 'codigo' =>'B40', 'descripcion' => 'kilogramo de fuerza por metro cuadrado'],
            ['id' =>297, 'codigo' =>'B41', 'descripcion' => 'kilojoule per kelvin'],
            ['id' =>298, 'codigo' =>'B42', 'descripcion' => 'kilojoule por kilogramo'],
            ['id' =>299, 'codigo' =>'B43', 'descripcion' => 'kilojoule por kilogramo kelvin'],
            ['id' =>300, 'codigo' =>'B44', 'descripcion' => 'kilojoule por mol'],
            ['id' =>301, 'codigo' =>'B45', 'descripcion' => 'kilomol'],
            ['id' =>302, 'codigo' =>'B46', 'descripcion' => 'kilomol por metro cúbico'],
            ['id' =>303, 'codigo' =>'B47', 'descripcion' => 'Kilonewton'],
            ['id' =>304, 'codigo' =>'B48', 'descripcion' => 'medidor de kilonewton'],
            ['id' =>305, 'codigo' =>'B49', 'descripcion' => 'kiloohm'],
            ['id' =>306, 'codigo' =>'B5', 'descripcion' => 'palanquilla'],
            ['id' =>307, 'codigo' =>'B50', 'descripcion' => 'medidor de kiloohm'],
            ['id' =>308, 'codigo' =>'B51', 'descripcion' => 'kilopond'],
            ['id' =>309, 'codigo' =>'B52', 'descripcion' => 'kilosegundo'],
            ['id' =>310, 'codigo' =>'B53', 'descripcion' => 'kilosiemens'],
            ['id' =>311, 'codigo' =>'B54', 'descripcion' => 'kilosiemens por metro'],
            ['id' =>312, 'codigo' =>'B55', 'descripcion' => 'kilovoltios por metro'],
            ['id' =>313, 'codigo' =>'B56', 'descripcion' => 'kiloveber por metro'],
            ['id' =>314, 'codigo' =>'B57', 'descripcion' => 'año luz'],
            ['id' =>315, 'codigo' =>'B58', 'descripcion' => 'litro por mol'],
            ['id' =>316, 'codigo' =>'B59', 'descripcion' => 'hora lumen'],
            ['id' =>317, 'codigo' =>'B6', 'descripcion' => 'bollo'],
            ['id' =>318, 'codigo' =>'B60', 'descripcion' => 'lumen por metro cuadrado'],
            ['id' =>319, 'codigo' =>'B61', 'descripcion' => 'lumen por vatio'],
            ['id' =>320, 'codigo' =>'B62', 'descripcion' => 'lumen segundo'],
            ['id' =>321, 'codigo' =>'B63', 'descripcion' => 'hora de lux'],
            ['id' =>322, 'codigo' =>'B64', 'descripcion' => 'lux segundo'],
            ['id' =>323, 'codigo' =>'B65', 'descripcion' => 'Maxwell'],
            ['id' =>324, 'codigo' =>'B66', 'descripcion' => 'megaamperios por metro cuadrado'],
            ['id' =>325, 'codigo' =>'B67', 'descripcion' => 'megabecquerel por kilogramo'],
            ['id' =>326, 'codigo' =>'B69', 'descripcion' => 'megacoulomb por metro cúbico'],
            ['id' =>327, 'codigo' =>'B7', 'descripcion' => 'ciclo'],
            ['id' =>328, 'codigo' =>'B70', 'descripcion' => 'megacoulomb por metro cuadrado'],
            ['id' =>329, 'codigo' =>'B71', 'descripcion' => 'megaelectronvolt'],
            ['id' =>330, 'codigo' =>'B72', 'descripcion' => 'megagramo por metro cúbico'],
            ['id' =>331, 'codigo' =>'B73', 'descripcion' => 'meganewton'],
            ['id' =>332, 'codigo' =>'B74', 'descripcion' => 'medidor de meganewton'],
            ['id' =>333, 'codigo' =>'B75', 'descripcion' => 'megaohm'],
            ['id' =>334, 'codigo' =>'B76', 'descripcion' => 'metro megaohm'],
            ['id' =>335, 'codigo' =>'B77', 'descripcion' => 'megasiemens por metro'],
            ['id' =>336, 'codigo' =>'B78', 'descripcion' => 'megavoltio'],
            ['id' =>337, 'codigo' =>'B79', 'descripcion' => 'megavolt por metro'],
            ['id' =>338, 'codigo' =>'B8', 'descripcion' => 'julios por metro cúbico'],
            ['id' =>339, 'codigo' =>'B81', 'descripcion' => 'metro recíproco cuadrado recíproco segundo'],
            ['id' =>340, 'codigo' =>'B83', 'descripcion' => 'metro a la cuarta potencia'],
            ['id' =>341, 'codigo' =>'B84', 'descripcion' => 'microamperios'],
            ['id' =>342, 'codigo' =>'B85', 'descripcion' => 'microbar'],
            ['id' =>343, 'codigo' =>'B86', 'descripcion' => 'microcoulomb'],
            ['id' =>344, 'codigo' =>'B87', 'descripcion' => 'microcoulomb por metro cúbico'],
            ['id' =>345, 'codigo' =>'B88', 'descripcion' => 'microcoulomb por metro cuadrado'],
            ['id' =>346, 'codigo' =>'B89', 'descripcion' => 'microfarada por metro'],
            ['id' =>347, 'codigo' =>'B9', 'descripcion' => 'batt'],
            ['id' =>348, 'codigo' =>'B90', 'descripcion' => 'microhenry'],
            ['id' =>349, 'codigo' =>'B91', 'descripcion' => 'microhenry por metro'],
            ['id' =>350, 'codigo' =>'B92', 'descripcion' => 'micronewton'],
            ['id' =>351, 'codigo' =>'B93', 'descripcion' => 'medidor de micronewton'],
            ['id' =>352, 'codigo' =>'B94', 'descripcion' => 'microohm'],
            ['id' =>353, 'codigo' =>'B95', 'descripcion' => 'medidor de microohmios'],
            ['id' =>354, 'codigo' =>'B96', 'descripcion' => 'micropascal'],
            ['id' =>355, 'codigo' =>'B97', 'descripcion' => 'microradiano'],
            ['id' =>356, 'codigo' =>'B98', 'descripcion' => 'microsegundo'],
            ['id' =>357, 'codigo' =>'B99', 'descripcion' => 'microsiemens'],
            ['id' =>358, 'codigo' =>'BAR', 'descripcion' => 'bar'],
            ['id' =>359, 'codigo' =>'BB', 'descripcion' => 'caja base'],
            ['id' =>360, 'codigo' =>'BD', 'descripcion' => 'tablero'],
            ['id' =>361, 'codigo' =>'SER', 'descripcion' => 'haz'],
            ['id' =>362, 'codigo' =>'BFT', 'descripcion' => 'pie de tabla'],
            ['id' =>363, 'codigo' =>'BG', 'descripcion' => 'bolso'],
            ['id' =>364, 'codigo' =>'BH', 'descripcion' => 'cepillo'],
            ['id' =>365, 'codigo' =>'BHP', 'descripcion' => 'potencia al freno'],
            ['id' =>366, 'codigo' =>'BIL', 'descripcion' => 'trillón de dólares'],
            ['id' =>367, 'codigo' =>'BJ', 'descripcion' => 'cangilón'],
            ['id' =>368, 'codigo' =>'BK', 'descripcion' => 'cesta'],
            ['id' =>369, 'codigo' =>'BL', 'descripcion' => 'bala'],
            ['id' =>370, 'codigo' =>'BLD', 'descripcion' => 'barril seco'],
            ['id' =>371, 'codigo' =>'BLL', 'descripcion' => 'barril (EE. UU.) (petróleo, etc.)'],
            ['id' =>372, 'codigo' =>'BO', 'descripcion' => 'botella'],
            ['id' =>373, 'codigo' =>'BP', 'descripcion' => 'cien pies de tabla'],
            ['id' =>374, 'codigo' =>'BQL', 'descripcion' => 'becquerel'],
            ['id' =>375, 'codigo' =>'BR', 'descripcion' => 'bar'],
            ['id' =>376, 'codigo' =>'BT', 'descripcion' => 'tornillo'],
            ['id' =>377, 'codigo' =>'BTU', 'descripcion' => 'Unidad Térmica Británica'],
            ['id' =>378, 'codigo' =>'BUA', 'descripcion' => 'bushel (EE. UU.)'],
            ['id' =>379, 'codigo' =>'BUI', 'descripcion' => 'bushel (Reino Unido)'],
            ['id' =>380, 'codigo' =>'BW', 'descripcion' => 'peso base'],
            ['id' =>381, 'codigo' =>'BX', 'descripcion' => 'caja'],
            ['id' =>382, 'codigo' =>'BZ', 'descripcion' => 'millones de BTUs'],
            ['id' =>383, 'codigo' =>'C0', 'descripcion' => 'llamada'],
            ['id' =>384, 'codigo' =>'C1', 'descripcion' => 'producto compuesto libra (peso total)'],
            ['id' =>385, 'codigo' =>'C10', 'descripcion' => 'millifarad'],
            ['id' =>386, 'codigo' =>'C11', 'descripcion' => 'miligal'],
            ['id' =>387, 'codigo' =>'C12', 'descripcion' => 'miligramo por metro'],
            ['id' =>388, 'codigo' =>'C13', 'descripcion' => 'miligray'],
            ['id' =>389, 'codigo' =>'C14', 'descripcion' => 'milihenry'],
            ['id' =>390, 'codigo' =>'C15', 'descripcion' => 'milijoule'],
            ['id' =>391, 'codigo' =>'C16', 'descripcion' => 'milímetro por segundo'],
            ['id' =>392, 'codigo' =>'C17', 'descripcion' => 'milímetro cuadrado por segundo'],
            ['id' =>393, 'codigo' =>'C18', 'descripcion' => 'milimol'],
            ['id' =>394, 'codigo' =>'C19', 'descripcion' => 'mol por kilogramo'],
            ['id' =>395, 'codigo' =>'C2', 'descripcion' => 'carset'],
            ['id' =>396, 'codigo' =>'C20', 'descripcion' => 'millinewton'],
            ['id' =>397, 'codigo' =>'C22', 'descripcion' => 'millinewton por metro'],
            ['id' =>398, 'codigo' =>'C23', 'descripcion' => 'medidor de miliohm'],
            ['id' =>399, 'codigo' =>'C24', 'descripcion' => 'segundo milipascal'],
            ['id' =>400, 'codigo' =>'C25', 'descripcion' => 'miliradian'],
            ['id' =>401, 'codigo' =>'C26', 'descripcion' => 'milisegundo'],
            ['id' =>402, 'codigo' =>'C27', 'descripcion' => 'milisiemens'],
            ['id' =>403, 'codigo' =>'C28', 'descripcion' => 'milisievert'],
            ['id' =>404, 'codigo' =>'C29', 'descripcion' => 'millitesla'],
            ['id' =>405, 'codigo' =>'C3', 'descripcion' => 'microvoltios por metro'],
            ['id' =>406, 'codigo' =>'C30', 'descripcion' => 'milivoltios por metro'],
            ['id' =>407, 'codigo' =>'C31', 'descripcion' => 'milivatios'],
            ['id' =>408, 'codigo' =>'C32', 'descripcion' => 'milivatios por metro cuadrado'],
            ['id' =>409, 'codigo' =>'C33', 'descripcion' => 'milliweber'],
            ['id' =>410, 'codigo' =>'C34', 'descripcion' => 'Topo'],
            ['id' =>411, 'codigo' =>'C35', 'descripcion' => 'mol por decímetro cúbico'],
            ['id' =>412, 'codigo' =>'C36', 'descripcion' => 'mol por metro cúbico'],
            ['id' =>413, 'codigo' =>'C38', 'descripcion' => 'mol por litro'],
            ['id' =>414, 'codigo' =>'C39', 'descripcion' => 'Nanoampere'],
            ['id' =>415, 'codigo' =>'C4', 'descripcion' => 'partido de carga'],
            ['id' =>416, 'codigo' =>'C40', 'descripcion' => 'nanocoulomb'],
            ['id' =>417, 'codigo' =>'C41', 'descripcion' => 'nanofarad'],
            ['id' =>418, 'codigo' =>'C42', 'descripcion' => 'nanofarad por metro'],
            ['id' =>419, 'codigo' =>'C43', 'descripcion' => 'nanohenry'],
            ['id' =>420, 'codigo' =>'C44', 'descripcion' => 'nanohenry por metro'],
            ['id' =>421, 'codigo' =>'C45', 'descripcion' => 'nanometro'],
            ['id' =>422, 'codigo' =>'C46', 'descripcion' => 'medidor de nanoohm'],
            ['id' =>423, 'codigo' =>'C47', 'descripcion' => 'nanosegundo'],
            ['id' =>424, 'codigo' =>'C48', 'descripcion' => 'nanotesla'],
            ['id' =>425, 'codigo' =>'C49', 'descripcion' => 'nanovatio'],
            ['id' =>426, 'codigo' =>'C5', 'descripcion' => 'costo'],
            ['id' =>427, 'codigo' =>'C50', 'descripcion' => 'neper'],
            ['id' =>428, 'codigo' =>'C51', 'descripcion' => 'neper por segundo'],
            ['id' =>429, 'codigo' =>'C52', 'descripcion' => 'picometro'],
            ['id' =>430, 'codigo' =>'C53', 'descripcion' => 'metro de newton segundo'],
            ['id' =>431, 'codigo' =>'C54', 'descripcion' => 'newton metro cuadrado kilogramo cuadrado'],
            ['id' =>432, 'codigo' =>'C55', 'descripcion' => 'newton por metro cuadrado'],
            ['id' =>433, 'codigo' =>'C56', 'descripcion' => 'newton por milímetro cuadrado'],
            ['id' =>434, 'codigo' =>'C57', 'descripcion' => 'newton segundo'],
            ['id' =>435, 'codigo' =>'C58', 'descripcion' => 'newton segundo por metro'],
            ['id' =>436, 'codigo' =>'C59', 'descripcion' => 'octava'],
            ['id' =>437, 'codigo' =>'C6', 'descripcion' => 'célula'],
            ['id' =>438, 'codigo' =>'C60', 'descripcion' => 'ohm centímetro'],
            ['id' =>439, 'codigo' =>'C61', 'descripcion' => 'ohm metro'],
            ['id' =>440, 'codigo' =>'C62', 'descripcion' => 'uno'],
            ['id' =>441, 'codigo' =>'C63', 'descripcion' => 'parsec'],
            ['id' =>442, 'codigo' =>'C64', 'descripcion' => 'pascal por kelvin'],
            ['id' =>443, 'codigo' =>'C65', 'descripcion' => 'segundo pascal'],
            ['id' =>444, 'codigo' =>'C66', 'descripcion' => 'segundo pascal por metro cúbico'],
            ['id' =>445, 'codigo' =>'C67', 'descripcion' => 'segundo pascal por metro'],
            ['id' =>446, 'codigo' =>'C68', 'descripcion' => 'petajoule'],
            ['id' =>447, 'codigo' =>'C69', 'descripcion' => 'telefono'],
            ['id' =>448, 'codigo' =>'C7', 'descripcion' => 'centipoise'],
            ['id' =>449, 'codigo' =>'C70', 'descripcion' => 'picoampere'],
            ['id' =>450, 'codigo' =>'C71', 'descripcion' => 'picocoulomb'],
            ['id' =>451, 'codigo' =>'C72', 'descripcion' => 'picofarad por metro'],
            ['id' =>452, 'codigo' =>'C73', 'descripcion' => 'picohenry'],
            ['id' =>453, 'codigo' =>'C75', 'descripcion' => 'picowatt'],
            ['id' =>454, 'codigo' =>'C76', 'descripcion' => 'picowatt por metro cuadrado'],
            ['id' =>455, 'codigo' =>'C77', 'descripcion' => 'medidor de libras'],
            ['id' =>456, 'codigo' =>'C78', 'descripcion' => 'fuerza de libra'],
            ['id' =>457, 'codigo' =>'C8', 'descripcion' => 'Millicoulomb por kilogramo'],
            ['id' =>458, 'codigo' =>'C80', 'descripcion' => 'rad'],
            ['id' =>459, 'codigo' =>'C81', 'descripcion' => 'radián'],
            ['id' =>460, 'codigo' =>'C82', 'descripcion' => 'medidor de radianes al cuadrado por mol'],
            ['id' =>461, 'codigo' =>'C83', 'descripcion' => 'medidor de radianes al cuadrado por kilogramo'],
            ['id' =>462, 'codigo' =>'C84', 'descripcion' => 'radian por metro'],
            ['id' =>463, 'codigo' =>'C85', 'descripcion' => 'â € ngstr recíproco “m'],
            ['id' =>464, 'codigo' =>'C86', 'descripcion' => 'metro cúbico recíproco'],
            ['id' =>465, 'codigo' =>'C87', 'descripcion' => 'metro cúbico recíproco por segundo'],
            ['id' =>466, 'codigo' =>'C88', 'descripcion' => 'voltios de electrones recíprocos por metro cúbico'],
            ['id' =>467, 'codigo' =>'C89', 'descripcion' => 'Henry Recíproco'],
            ['id' =>468, 'codigo' =>'C9', 'descripcion' => 'grupo de bobina'],
            ['id' =>469, 'codigo' =>'C90', 'descripcion' => 'Joule recíproco por metro cúbico'],
            ['id' =>470, 'codigo' =>'C91', 'descripcion' => 'kelvin recíproco o kelvin al poder menos uno'],
            ['id' =>471, 'codigo' =>'C92', 'descripcion' => 'medidor recíproco'],
            ['id' =>472, 'codigo' =>'C93', 'descripcion' => 'metro cuadrado recíproco'],
            ['id' =>473, 'codigo' =>'C94', 'descripcion' => 'minuto recíproco'],
            ['id' =>474, 'codigo' =>'C95', 'descripcion' => 'mole recíproco'],
            ['id' =>475, 'codigo' =>'C96', 'descripcion' => 'Pascal recíproco o pascal a la potencia menos uno.'],
            ['id' =>476, 'codigo' =>'C97', 'descripcion' => 'segundo recíproco'],
            ['id' =>477, 'codigo' =>'C98', 'descripcion' => 'segundo recíproco por metro cúbico'],
            ['id' =>478, 'codigo' =>'C99', 'descripcion' => 'segundo recíproco por metro cuadrado'],
            ['id' =>479, 'codigo' =>'CA', 'descripcion' => 'Caja'],
            ['id' =>480, 'codigo' =>'CCT', 'descripcion' => 'Capacidad de carga en toneladas métricas.'],
            ['id' =>481, 'codigo' =>'CDL', 'descripcion' => 'candela'],
            ['id' =>482, 'codigo' =>'CEL', 'descripcion' => 'grado Celsius'],
            ['id' =>483, 'codigo' =>'CEN', 'descripcion' => 'cien'],
            ['id' =>484, 'codigo' =>'CG', 'descripcion' => 'tarjeta'],
            ['id' =>485, 'codigo' =>'CGM', 'descripcion' => 'centigramo'],
            ['id' =>486, 'codigo' =>'CH', 'descripcion' => 'envase'],
            ['id' =>487, 'codigo' =>'CJ', 'descripcion' => 'cono'],
            ['id' =>488, 'codigo' =>'CK', 'descripcion' => 'conector'],
            ['id' =>489, 'codigo' =>'CKG', 'descripcion' => 'Coulomb por kilogramo'],
            ['id' =>490, 'codigo' =>'CL', 'descripcion' => 'bobina'],
            ['id' =>491, 'codigo' =>'CLF', 'descripcion' => 'cientos de licencia'],
            ['id' =>492, 'codigo' =>'CLT', 'descripcion' => 'centilitro'],
            ['id' =>493, 'codigo' =>'CMK', 'descripcion' => 'centímetro cuadrado'],
            ['id' =>494, 'codigo' =>'CMQ', 'descripcion' => 'centímetro cúbico'],
            ['id' =>495, 'codigo' =>'CMT', 'descripcion' => 'centímetro'],
            ['id' =>496, 'codigo' =>'CNP', 'descripcion' => 'paquete de cien'],
            ['id' =>497, 'codigo' =>'CNT', 'descripcion' => 'Cental (Reino Unido)'],
            ['id' =>498, 'codigo' =>'CO', 'descripcion' => 'garrafón'],
            ['id' =>499, 'codigo' =>'COU', 'descripcion' => 'culombio'],
            ['id' =>500, 'codigo' =>'CQ', 'descripcion' => 'cartucho'],
            ['id' =>501, 'codigo' =>'CR', 'descripcion' => 'caja'],
            ['id' =>502, 'codigo' =>'CS', 'descripcion' => 'caso'],
            ['id' =>503, 'codigo' =>'CT', 'descripcion' => 'caja de cartón'],
            ['id' =>504, 'codigo' =>'CTM', 'descripcion' => 'quilate métrico'],
            ['id' =>505, 'codigo' =>'CU', 'descripcion' => 'vaso'],
            ['id' =>506, 'codigo' =>'CUR', 'descripcion' => 'curie'],
            ['id' =>507, 'codigo' =>'CV', 'descripcion' => 'cubrir'],
            ['id' =>508, 'codigo' =>'CWA', 'descripcion' => 'cien libras (quintales) / cien pesos (US)'],
            ['id' =>509, 'codigo' =>'CWI', 'descripcion' => 'cien pesos (Reino Unido)'],
            ['id' =>510, 'codigo' =>'CY', 'descripcion' => 'cilindro'],
            ['id' =>511, 'codigo' =>'CZ', 'descripcion' => 'combo'],
            ['id' =>512, 'codigo' =>'D1', 'descripcion' => 'segundo recíproco por esteradiano'],
            ['id' =>513, 'codigo' =>'D10', 'descripcion' => 'siemens por metro'],
            ['id' =>514, 'codigo' =>'D12', 'descripcion' => 'siemens metro cuadrado por mol'],
            ['id' =>515, 'codigo' =>'D13', 'descripcion' => 'sievert'],
            ['id' =>516, 'codigo' =>'D14', 'descripcion' => 'mil yardas lineales'],
            ['id' =>517, 'codigo' =>'D15', 'descripcion' => 'sone'],
            ['id' =>518, 'codigo' =>'D16', 'descripcion' => 'centímetro cuadrado por ergio'],
            ['id' =>519, 'codigo' =>'D17', 'descripcion' => 'centímetro cuadrado por erg esterlina'],
            ['id' =>520, 'codigo' =>'D18', 'descripcion' => 'metro kelvin'],
            ['id' =>521, 'codigo' =>'D19', 'descripcion' => 'kelvin metro cuadrado por vatio'],
            ['id' =>522, 'codigo' =>'D2', 'descripcion' => 'segundo recíproco por metros cuadrados esteradianos'],
            ['id' =>523, 'codigo' =>'D20', 'descripcion' => 'metro cuadrado por julio'],
            ['id' =>524, 'codigo' =>'D21', 'descripcion' => 'metro cuadrado por kilogramo'],
            ['id' =>525, 'codigo' =>'D22', 'descripcion' => 'metro cuadrado por mol'],
            ['id' =>526, 'codigo' =>'D23', 'descripcion' => 'pluma gramo (proteína)'],
            ['id' =>527, 'codigo' =>'D24', 'descripcion' => 'metro cuadrado por esterilizador'],
            ['id' =>528, 'codigo' =>'D25', 'descripcion' => 'metro cuadrado por julios esteradianos'],
            ['id' =>529, 'codigo' =>'D26', 'descripcion' => 'metro cuadrado por voltio segundo'],
            ['id' =>530, 'codigo' =>'D27', 'descripcion' => 'esteradiano'],
            ['id' =>531, 'codigo' =>'D28', 'descripcion' => 'sifón'],
            ['id' =>532, 'codigo' =>'D29', 'descripcion' => 'terahercios'],
            ['id' =>533, 'codigo' =>'D30', 'descripcion' => 'terajulio'],
            ['id' =>534, 'codigo' =>'D31', 'descripcion' => 'teravatio'],
            ['id' =>535, 'codigo' =>'D32', 'descripcion' => 'hora de teravatio'],
            ['id' =>536, 'codigo' =>'D33', 'descripcion' => 'tesla'],
            ['id' =>537, 'codigo' =>'D34', 'descripcion' => 'Texas'],
            ['id' =>538, 'codigo' =>'D35', 'descripcion' => 'caloría termoquímica'],
            ['id' =>539, 'codigo' =>'D37', 'descripcion' => 'caloría termoquímica por gramo kelvin'],
            ['id' =>540, 'codigo' =>'D38', 'descripcion' => 'calorías termoquímicas por segundo centímetro kelvin'],
            ['id' =>541, 'codigo' =>'D39', 'descripcion' => 'calorías termoquímicas por segundo centímetro cuadrado kelvin'],
            ['id' =>542, 'codigo' =>'D40', 'descripcion' => 'mil litros'],
            ['id' =>543, 'codigo' =>'D41', 'descripcion' => 'tonelada por metro cúbico'],
            ['id' =>544, 'codigo' =>'D42', 'descripcion' => 'año tropical'],
            ['id' =>545, 'codigo' =>'D43', 'descripcion' => 'unidad de masa atómica unificada'],
            ['id' =>546, 'codigo' =>'D44', 'descripcion' => 'var'],
            ['id' =>547, 'codigo' =>'D45', 'descripcion' => 'voltios al cuadrado por kelvin al cuadrado'],
            ['id' =>548, 'codigo' =>'D46', 'descripcion' => 'voltio – amperio'],
            ['id' =>549, 'codigo' =>'D47', 'descripcion' => 'voltio por centímetro'],
            ['id' =>550, 'codigo' =>'D48', 'descripcion' => 'voltio por kelvin'],
            ['id' =>551, 'codigo' =>'D49', 'descripcion' => 'milivoltios por kelvin'],
            ['id' =>552, 'codigo' =>'D5', 'descripcion' => 'kilogramo por centímetro cuadrado'],
            ['id' =>553, 'codigo' =>'D50', 'descripcion' => 'voltios por metro'],
            ['id' =>554, 'codigo' =>'D51', 'descripcion' => 'voltios por milímetro'],
            ['id' =>555, 'codigo' =>'D52', 'descripcion' => 'vatios por kelvin'],
            ['id' =>556, 'codigo' =>'D53', 'descripcion' => 'vatios por metro kelvin'],
            ['id' =>557, 'codigo' =>'D54', 'descripcion' => 'vatios por metro cuadrado'],
            ['id' =>558, 'codigo' =>'D55', 'descripcion' => 'vatios por metro cuadrado kelvin'],
            ['id' =>559, 'codigo' =>'D56', 'descripcion' => 'vatios por metro cuadrado de kelvin a la cuarta potencia'],
            ['id' =>560, 'codigo' =>'D57', 'descripcion' => 'vatios por steradian'],
            ['id' =>561, 'codigo' =>'D58', 'descripcion' => 'vatios por metro cuadrado esterlino'],
            ['id' =>562, 'codigo' =>'D59', 'descripcion' => 'weber por metro'],
            ['id' =>563, 'codigo' =>'D6', 'descripcion' => 'röntgen por segundo'],
            ['id' =>564, 'codigo' =>'D60', 'descripcion' => 'weber por milímetro'],
            ['id' =>565, 'codigo' =>'D61', 'descripcion' => 'minuto'],
            ['id' =>566, 'codigo' =>'D62', 'descripcion' => 'segundo'],
            ['id' =>567, 'codigo' =>'D63', 'descripcion' => 'libro'],
            ['id' =>568, 'codigo' =>'D64', 'descripcion' => 'bloquear'],
            ['id' =>569, 'codigo' =>'D65', 'descripcion' => 'redondo'],
            ['id' =>570, 'codigo' =>'D66', 'descripcion' => 'casete'],
            ['id' =>571, 'codigo' =>'D67', 'descripcion' => 'dólar por hora'],
            ['id' =>572, 'codigo' =>'D69', 'descripcion' => 'pulgada a la cuarta potencia'],
            ['id' =>573, 'codigo' =>'D7', 'descripcion' => 'Sandwich'],
            ['id' =>574, 'codigo' =>'D70', 'descripcion' => 'Tabla Internacional (IT) caloría'],
            ['id' =>575, 'codigo' =>'D71', 'descripcion' => 'Tabla Internacional (IT) calorías por segundo centímetro kelvin'],
            ['id' =>576, 'codigo' =>'D72', 'descripcion' => 'Tabla Internacional (IT) calorías por segundo centímetro cuadrado kelvin'],
            ['id' =>577, 'codigo' =>'D73', 'descripcion' => 'joule metro cuadrado'],
            ['id' =>578, 'codigo' =>'D74', 'descripcion' => 'kilogramo por mol'],
            ['id' =>579, 'codigo' =>'D75', 'descripcion' => 'Tabla Internacional (IT) calorías por gramo'],
            ['id' =>580, 'codigo' =>'D76', 'descripcion' => 'Tabla Internacional (IT) calorías por gramo kelvin'],
            ['id' =>581, 'codigo' =>'D77', 'descripcion' => 'megacoulomb'],
            ['id' =>582, 'codigo' =>'D79', 'descripcion' => 'haz'],
            ['id' =>583, 'codigo' =>'D8', 'descripcion' => 'puntaje de drenaje'],
            ['id' =>584, 'codigo' =>'D80', 'descripcion' => 'microwatt'],
            ['id' =>585, 'codigo' =>'D81', 'descripcion' => 'microtesla'],
            ['id' =>586, 'codigo' =>'D82', 'descripcion' => 'microvoltio'],
            ['id' =>587, 'codigo' =>'D83', 'descripcion' => 'medidor de millinewton'],
            ['id' =>588, 'codigo' =>'D85', 'descripcion' => 'microwatt por metro cuadrado'],
            ['id' =>589, 'codigo' =>'D86', 'descripcion' => 'Millicoulomb'],
            ['id' =>590, 'codigo' =>'D87', 'descripcion' => 'milimol por kilogramo'],
            ['id' =>591, 'codigo' =>'D88', 'descripcion' => 'millicoulomb por metro cúbico'],
            ['id' =>592, 'codigo' =>'D89', 'descripcion' => 'millicoulomb por metro cuadrado'],
            ['id' =>593, 'codigo' =>'D9', 'descripcion' => 'dina por centímetro cuadrado'],
            ['id' =>594, 'codigo' =>'D90', 'descripcion' => 'metro cúbico (neto)'],
            ['id' =>595, 'codigo' =>'D91', 'descripcion' => 'movimiento rápido del ojo'],
            ['id' =>596, 'codigo' =>'D92', 'descripcion' => 'banda'],
            ['id' =>597, 'codigo' =>'D93', 'descripcion' => 'segundo por metro cúbico'],
            ['id' =>598, 'codigo' =>'D94', 'descripcion' => 'segundo por metro cúbico radianes'],
            ['id' =>599, 'codigo' =>'D95', 'descripcion' => 'julios por gramo'],
            ['id' =>600, 'codigo' =>'D96', 'descripcion' => 'libra bruta'],
            ['id' =>601, 'codigo' =>'D97', 'descripcion' => 'carga de palet / unidad'],
            ['id' =>602, 'codigo' =>'D98', 'descripcion' => 'libra de masa'],
            ['id' =>603, 'codigo' =>'D99', 'descripcion' => 'manga'],
            ['id' =>604, 'codigo' =>'DAA', 'descripcion' => 'despreciar'],
            ['id' =>605, 'codigo' =>'DAD', 'descripcion' => 'diez dias'],
            ['id' =>606, 'codigo' =>'DAY', 'descripcion' => 'día'],
            ['id' =>607, 'codigo' =>'DB', 'descripcion' => 'libra seca'],
            ['id' =>608, 'codigo' =>'DC', 'descripcion' => 'disco'],
            ['id' =>609, 'codigo' =>'DD', 'descripcion' => 'la licenciatura'],
            ['id' =>610, 'codigo' =>'DE', 'descripcion' => 'acuerdo'],
            ['id' =>611, 'codigo' =>'DEC', 'descripcion' => 'década'],
            ['id' =>612, 'codigo' =>'DG', 'descripcion' => 'decigramo'],
            ['id' =>613, 'codigo' =>'DI', 'descripcion' => 'dispensador'],
            ['id' =>614, 'codigo' =>'DJ', 'descripcion' => 'decagramo'],
            ['id' =>615, 'codigo' =>'DLT', 'descripcion' => 'decilitro'],
            ['id' =>616, 'codigo' =>'DMK', 'descripcion' => '250nformaci cuadrado'],
            ['id' =>617, 'codigo' =>'DMQ', 'descripcion' => 'decímetro cúbico'],
            ['id' =>618, 'codigo' =>'DMT', 'descripcion' => 'decímetro'],
            ['id' =>619, 'codigo' =>'DN', 'descripcion' => 'medidor de decinewton'],
            ['id' =>620, 'codigo' =>'DPC', 'descripcion' => 'docena pieza'],
            ['id' =>621, 'codigo' =>'DPR', 'descripcion' => 'docena par'],
            ['id' =>622, 'codigo' =>'DPT', 'descripcion' => 'tonelaje de desplazamiento'],
            ['id' =>623, 'codigo' =>'DQ', 'descripcion' => 'registro de datos'],
            ['id' =>624, 'codigo' =>'DR', 'descripcion' => 'tambor'],
            ['id' =>625, 'codigo' =>'DRA', 'descripcion' => 'dram (US)'],
            ['id' =>626, 'codigo' =>'DRI', 'descripcion' => 'dram (Reino Unido)'],
            ['id' =>627, 'codigo' =>'DRL', 'descripcion' => 'docena rollo'],
            ['id' =>628, 'codigo' =>'DRM', 'descripcion' => 'dracma (Reino Unido)'],
            ['id' =>629, 'codigo' =>'DS', 'descripcion' => 'monitor'],
            ['id' =>630, 'codigo' =>'DT', 'descripcion' => 'tonelada seca'],
            ['id' =>631, 'codigo' =>'DTN', 'descripcion' => 'Decitonne'],
            ['id' =>632, 'codigo' =>'DU', 'descripcion' => 'dina'],
            ['id' =>633, 'codigo' =>'DWT', 'descripcion' => 'pennyweight'],
            ['id' =>634, 'codigo' =>'DX', 'descripcion' => 'dina por centímetro'],
            ['id' =>635, 'codigo' =>'DY', 'descripcion' => 'libro de directorio'],
            ['id' =>636, 'codigo' =>'DZN', 'descripcion' => 'docena'],
            ['id' =>637, 'codigo' =>'DZP', 'descripcion' => 'paquete de doce'],
            ['id' =>638, 'codigo' =>'E2', 'descripcion' => 'cinturón'],
            ['id' =>639, 'codigo' =>'E3', 'descripcion' => 'remolque'],
            ['id' =>640, 'codigo' =>'E4', 'descripcion' => 'kilogramo bruto'],
            ['id' =>641, 'codigo' =>'E5', 'descripcion' => 'tonelada métrica larga'],
            ['id' =>642, 'codigo' =>'EA', 'descripcion' => 'cada'],
            ['id' =>643, 'codigo' =>'EB', 'descripcion' => 'casilla de correo electrónico'],
            ['id' =>644, 'codigo' =>'CE', 'descripcion' => 'cada uno por mes'],
            ['id' =>645, 'codigo' =>'EP', 'descripcion' => 'paquete de once'],
            ['id' =>646, 'codigo' =>'EQ', 'descripcion' => 'galón equivalente'],
            ['id' =>647, 'codigo' =>'EV', 'descripcion' => 'sobre'],
            ['id' =>648, 'codigo' =>'F1', 'descripcion' => 'mil pies cúbicos por día'],
            ['id' =>649, 'codigo' =>'F9', 'descripcion' => 'Fibra por centímetro cúbico de aire'],
            ['id' =>650, 'codigo' =>'FAH', 'descripcion' => 'grado Fahrenheit'],
            ['id' =>651, 'codigo' =>'FAR', 'descripcion' => 'faradio'],
            ['id' =>652, 'codigo' =>'FB', 'descripcion' => 'campo'],
            ['id' =>653, 'codigo' =>'FC', 'descripcion' => 'mil pies cúbicos'],
            ['id' =>654, 'codigo' =>'FD', 'descripcion' => 'millón de partículas por pie cúbico'],
            ['id' =>655, 'codigo' =>'FE', 'descripcion' => 'pie de pista'],
            ['id' =>656, 'codigo' =>'FF', 'descripcion' => 'cien metros cúbicos'],
            ['id' =>657, 'codigo' =>'FG', 'descripcion' => 'parche transdérmico'],
            ['id' =>658, 'codigo' =>'FH', 'descripcion' => 'micromol'],
            ['id' =>659, 'codigo' =>'FL', 'descripcion' => 'tonelada en escamas'],
            ['id' =>660, 'codigo' =>'FM', 'descripcion' => 'millones de pies cúbicos'],
            ['id' =>661, 'codigo' =>'FOT', 'descripcion' => 'pie'],
            ['id' =>662, 'codigo' =>'FP', 'descripcion' => 'libra por pie cuadrado'],
            ['id' =>663, 'codigo' =>'FR', 'descripcion' => 'pie por minuto'],
            ['id' =>664, 'codigo' =>'FS', 'descripcion' => 'pie por segundo'],
            ['id' =>665, 'codigo' =>'FTK', 'descripcion' => 'pie cuadrado'],
            ['id' =>666, 'codigo' =>'FTQ', 'descripcion' => 'pie cubico'],
            ['id' =>667, 'codigo' =>'G2', 'descripcion' => 'US galones por minuto'],
            ['id' =>668, 'codigo' =>'G3', 'descripcion' => 'Galon imperial por minuto'],
            ['id' =>669, 'codigo' =>'G7', 'descripcion' => 'hoja de microficha'],
            ['id' =>670, 'codigo' =>'GB', 'descripcion' => 'galón (US) por día'],
            ['id' =>671, 'codigo' =>'GBQ', 'descripcion' => 'gigabecquerel'],
            ['id' =>672, 'codigo' =>'GC', 'descripcion' => 'gramo por 100 gramo'],
            ['id' =>673, 'codigo' =>'GD', 'descripcion' => 'barril bruto'],
            ['id' =>674, 'codigo' =>'GE', 'descripcion' => 'libra por galón (US)'],
            ['id' =>675, 'codigo' =>'GF', 'descripcion' => 'gramo por metro (gramo por 100 centímetros)'],
            ['id' =>676, 'codigo' =>'GFI', 'descripcion' => 'gramo de isótopo fisionable'],
            ['id' =>677, 'codigo' =>'GGR', 'descripcion' => 'gramo'],
            ['id' =>678, 'codigo' =>'GH', 'descripcion' => 'medio galón (EE. UU.)'],
            ['id' =>679, 'codigo' =>'GIA', 'descripcion' => 'branquias'],
            ['id' =>680, 'codigo' =>'GII', 'descripcion' => 'Gill (Reino Unido)'],
            ['id' =>681, 'codigo' =>'GJ', 'descripcion' => 'gramo por mililitro'],
            ['id' =>682, 'codigo' =>'G K', 'descripcion' => 'gramo por kilogramo'],
            ['id' =>683, 'codigo' =>'GL', 'descripcion' => 'gramo por litro'],
            ['id' =>684, 'codigo' =>'GLD', 'descripcion' => 'galón seco (EE. UU.)'],
            ['id' =>685, 'codigo' =>'GLI', 'descripcion' => 'galón (Reino Unido)'],
            ['id' =>686, 'codigo' =>'GLL', 'descripcion' => 'galón'],
            ['id' =>687, 'codigo' =>'GM', 'descripcion' => 'gramo por metro cuadrado'],
            ['id' =>688, 'codigo' =>'GN', 'descripcion' => 'galón bruto'],
            ['id' =>689, 'codigo' =>'GO', 'descripcion' => 'miligramos por metro cuadrado'],
            ['id' =>690, 'codigo' =>'GP', 'descripcion' => 'miligramo por metro cúbico'],
            ['id' =>691, 'codigo' =>'GQ', 'descripcion' => 'microgramos por metro cúbico'],
            ['id' =>692, 'codigo' =>'GRM', 'descripcion' => 'gramo'],
            ['id' =>693, 'codigo' =>'GRN', 'descripcion' => 'grano'],
            ['id' =>694, 'codigo' =>'GRO', 'descripcion' => 'bruto'],
            ['id' =>695, 'codigo' =>'GRT', 'descripcion' => 'tonelada de registro bruto'],
            ['id' =>696, 'codigo' =>'GT', 'descripcion' => 'tonelada bruta'],
            ['id' =>697, 'codigo' =>'GV', 'descripcion' => 'gigajoule'],
            ['id' =>698, 'codigo' =>'GW', 'descripcion' => 'galón por mil pies cúbicos'],
            ['id' =>699, 'codigo' =>'GWH', 'descripcion' => 'hora de gigavatios'],
            ['id' =>700, 'codigo' =>'GY', 'descripcion' => 'patio bruto'],
            ['id' =>701, 'codigo' =>'GZ', 'descripcion' => 'sistema de medición'],
            ['id' =>702, 'codigo' =>'H1', 'descripcion' => 'media página – electrónica'],
            ['id' =>703, 'codigo' =>'H2', 'descripcion' => 'medio litro'],
            ['id' =>704, 'codigo' =>'HA', 'descripcion' => 'madeja'],
            ['id' =>705, 'codigo' =>'HAR', 'descripcion' => 'hectárea'],
            ['id' =>706, 'codigo' =>'HBA', 'descripcion' => 'hectobar'],
            ['id' =>707, 'codigo' =>'HBX', 'descripcion' => 'cien cajas'],
            ['id' =>708, 'codigo' =>'HC', 'descripcion' => 'cien cuentas'],
            ['id' =>709, 'codigo' =>'HD', 'descripcion' => 'media docena'],
            ['id' =>710, 'codigo' =>'ÉL', 'descripcion' => 'centésima de quilate'],
            ['id' =>711, 'codigo' =>'HF', 'descripcion' => 'cien pies'],
            ['id' =>712, 'codigo' =>'HGM', 'descripcion' => 'hectogramo'],
            ['id' =>713, 'codigo' =>'HH', 'descripcion' => 'cien pies cúbicos'],
            ['id' =>714, 'codigo' =>'HI', 'descripcion' => 'cien hojas'],
            ['id' =>715, 'codigo' =>'HIU', 'descripcion' => 'cien unidades internacionales'],
            ['id' =>716, 'codigo' =>'HJ', 'descripcion' => 'caballo métrico'],
            ['id' =>717, 'codigo' =>'HK', 'descripcion' => 'cien kilogramos'],
            ['id' =>718, 'codigo' =>'HL', 'descripcion' => 'cien pies (lineales)'],
            ['id' =>719, 'codigo' =>'HLT', 'descripcion' => 'hectolitro'],
            ['id' =>720, 'codigo' =>'HM', 'descripcion' => 'milla por hora'],
            ['id' =>721, 'codigo' =>'HMQ', 'descripcion' => 'millones de metros cúbicos'],
            ['id' =>722, 'codigo' =>'HMT', 'descripcion' => 'hectómetro'],
            ['id' =>723, 'codigo' =>'HN', 'descripcion' => 'milímetro convencional de mercurio'],
            ['id' =>724, 'codigo' =>'HO', 'descripcion' => 'cien onzas troy'],
            ['id' =>725, 'codigo' =>'HP', 'descripcion' => 'milímetro convencional de agua'],
            ['id' =>726, 'codigo' =>'HPA', 'descripcion' => 'hectolitro de alcohol puro'],
            ['id' =>727, 'codigo' =>'HS', 'descripcion' => 'cien pies cuadrados'],
            ['id' =>728, 'codigo' =>'HT', 'descripcion' => 'media hora'],
            ['id' =>729, 'codigo' =>'HTZ', 'descripcion' => 'hertz'],

        ]);
    }
}